export const INDUSTRY_MAP = {
  "Financial Services & Banking": ["finance", "financial", "banking", "investment", "hedge fund", "private equity", "wealth management", "capital markets", "fintech", "accounting", "goldman", "jpmorgan", "morgan stanley", "blackrock", "fidelity"],
  "Consulting": ["consulting", "consultant", "consultancy", "advisory", "mckinsey", "bain", "bcg", "deloitte", "pwc", "kpmg", "ey", "ernst", "strategy", "accenture"],
  "Technology & Software": ["technology", "software", "engineering", "developer", "product", "saas", "cloud", "ai", "machine learning", "data", "tech", "startup", "it", "information technology", "google", "microsoft", "apple", "meta", "amazon"],
  "Healthcare & Life Sciences": ["healthcare", "health", "hospital", "medical", "clinical", "nursing", "physician", "health system", "pharma", "biotech"],
  "Media & Entertainment": ["media", "entertainment", "film", "television", "streaming", "publishing", "content", "journalism", "broadcast", "disney", "netflix", "warner"],
  "Consumer Goods & Retail": ["consumer", "retail", "brand", "cpg", "fmcg", "e-commerce", "merchandising", "buying", "nike", "target", "walmart", "supplier", "manufacturer", "manufacturing", "wholesale", "distribution"],
  "Real Estate": ["real estate", "realty", "property", "development", "construction", "leasing", "brokerage", "cbre", "jll"],
  "Energy & Utilities": ["energy", "oil", "gas", "renewable", "solar", "utilities", "power", "exxon", "chevron"],
  "Government & Nonprofit": ["government", "nonprofit", "non-profit", "public sector", "federal", "state", "municipal", "ngo", "policy", "charity"],
  "Logistics & Supply Chain": ["logistics", "supply chain", "operations", "procurement", "sourcing", "distribution", "warehouse", "fedex", "ups", "supplier", "manufacturer"],
  "Sports & Athletics": ["sports", "athletics", "nfl", "nba", "mlb", "nhl", "espn", "team", "league", "athletic"],
  "Legal & Compliance": ["legal", "law", "legal services", "law & legal", "law and legal", "compliance", "counsel", "attorney", "lawyer", "paralegal", "litigation", "regulatory"],
  "Marketing & Brand": ["marketing", "brand", "advertising", "pr", "communications", "growth", "content", "social media", "digital", "creative"],
  "Engineering": ["engineering", "engineer", "mechanical", "civil", "electrical", "chemical", "aerospace", "manufacturing"],
  "Pre-Med & Healthcare": ["pre-med", "premed", "medical school", "clinical", "research", "laboratory"],
  "Hospitality & Tourism": ["hospitality", "hotel", "restaurant", "travel", "tourism", "events", "food", "beverage"],
  "Education": ["education", "teaching", "school", "university", "academic", "curriculum", "edtech"],
  "Human Resources": ["human resources", "hr", "recruiting", "talent", "people ops", "organizational"],
  "Nonprofit & Social Impact": ["nonprofit", "non-profit", "social impact", "mission", "ngo", "foundation", "charity", "advocacy"],
  "Architecture & Design": ["architecture", "design", "interior", "urban planning", "landscape", "studio"],
  "Biotech & Life Sciences": ["biotech", "life sciences", "genomics", "pharmaceutical", "drug discovery", "clinical trials"],
};