import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// School code to display name mapping
const SCHOOL_NAMES = {
  ucf: 'University of Central Florida',
  ufl: 'University of Florida',
  fsu: 'Florida State University',
  fau: 'Florida Atlantic University',
  usf: 'University of South Florida',
  usc: 'University of Southern California',
  umich: 'University of Michigan',
  osu: 'Ohio State University',
  psu: 'Penn State University',
  umd: 'University of Maryland',
  udel: 'University of Delaware',
  uga: 'University of Georgia',
  tulane: 'Tulane University',
  uky: 'University of Kentucky',
  jmu: 'James Madison University',
  utexas: 'University of Texas',
  miami: 'University of Miami',
  usc_columbia: 'University of South Carolina',
  cornell: 'Cornell University',
};

// CSV data: email -> school_code (only non-UFL entries)
const CSV_DATA = [
  { email: 'shell147@zoominternet.net', school: 'udel' },
  { email: 'lisaromanlucci@gmail.com', school: 'udel' },
  { email: '4gtpyhj2yt@privaterelay.appleid.com', school: 'udel' },
  { email: 'franbloom13@gmail.com', school: 'umd' },
  { email: 'mardochee.renaudin@gmail.com', school: 'ucf' },
  { email: 'ljgarten@gmail.com', school: 'umich' },
  { email: 'morganhurst29@gmail.com', school: 'umich' },
  { email: 'amykates@optonline.net', school: 'umich' },
  { email: 'bonnie.hurst@sbcglobal.net', school: 'umich' },
  { email: 'ztqwpbst9f@privaterelay.appleid.com', school: 'umich' },
  { email: '9z7bnm7n7j@privaterelay.appleid.com', school: 'fau' },
  { email: 'carlymaass@gmail.com', school: 'psu' },
  { email: 'larchbol@yahoo.com', school: 'umich' },
  { email: 'kapplauren@gmail.com', school: 'psu' },
  { email: 'heidihdross@gmail.com', school: 'umd' },
  { email: 'tovi.taylor@gmail.com', school: 'udel' },
  { email: 'mweyl25@gmail.com', school: 'udel' },
  { email: 'jill@uffastforward.com', school: 'usc' },
  { email: 'jodi.leone@gmail.com', school: 'umich' },
  { email: 'brian.dickstein1@gmail.com', school: 'umich' },
  { email: 'marni@llpaint.com', school: 'umich' },
  { email: 'ndtabs@verizon.net', school: 'umich' },
  { email: 'jenolarsch@gmail.com', school: 'umich' },
  { email: 'zachary.zimmerman@cantor.com', school: 'umich' },
  { email: 'barrifruitbine@gmail.com', school: 'utexas' },
  { email: 'tfhertwig@msn.com', school: 'psu' },
  { email: 'tkollinsmith@gmail.com', school: 'umich' },
  { email: 'charnasfamily5@gmail.com', school: 'umich' },
  { email: 'hopespiller@gmail.com', school: 'umich' },
  { email: 'blain.aleah@gmail.com', school: 'ucf' },
  { email: 'selenamarievk@gmail.com', school: 'umich' },
  { email: 'jilevine@optonline.net', school: 'umich' },
  { email: 'mayolfamily@bellsouth.net', school: 'umich' },
  { email: 'nuglou@gmail.com', school: 'umich' },
  { email: 'lsimkuspaskola@gmail.com', school: 'umich' },
  { email: 'hillary523@icloud.com', school: 'umich' },
  { email: 'alyssa@allaboutadmissions.com', school: 'umich' },
  { email: 'stalburg@gmail.com', school: 'umich' },
  { email: 'ericayaker@binghamcounseling.com', school: 'umich' },
  { email: 'tarynschaffer@gmail.com', school: 'umich' },
  { email: 'debsimp@optonline.net', school: 'osu' },
  { email: 'h49v2pttkf@privaterelay.appleid.com', school: 'umich' },
  { email: 'lorijrosen@gmail.com', school: 'umich' },
  { email: 'goldy3b24@gmail.com', school: 'osu' },
  { email: 'bonniekatz38@aol.com', school: 'umich' },
  { email: 'dibeerman@hotmail.com', school: 'umich' },
  { email: 'jdheimowitz@bellsouth.net', school: 'umich' },
  { email: 'mattlevin1111@gmail.com', school: 'umich' },
  { email: 'sallygainesmoorhead@gmail.com', school: 'umich' },
  { email: 'ppardes1026@gmail.com', school: 'umich' },
  { email: 'carynfitzgerald8@gmail.com', school: 'umich' },
  { email: 'rachelstahler@gmail.com', school: 'umich' },
  { email: 'tjnaugh14@gmail.com', school: 'umich' },
  { email: 'sivin@optonline.net', school: 'umich' },
  { email: 'fk72vrck99@privaterelay.appleid.com', school: 'fau' },
  { email: 'simpkins02@yahoo.com', school: 'usc' },
  { email: 'dahliatop@gmail.com', school: 'umd' },
  { email: 'eachance1@gmail.com', school: 'ucf' },
  { email: 'kimedel@gmail.com', school: 'fsu' },
  { email: 'michellerbrady@hotmail.com', school: 'ucf' },
  { email: 'amandabrown05@yahoo.com', school: 'ucf' },
  { email: 'miguel.sanchezm2002@gmail.com', school: 'ucf' },
  { email: 'collegefastforward.untimely030@passfwd.com', school: 'ucf' },
  { email: 'schristenson@aerospace-policy.org', school: 'ucf' },
  { email: 'woodamandaa@gmail.com', school: 'ucf' },
  { email: 'mcampbell1@bellsouth.net', school: 'ucf' },
  { email: 'judeambrose@icloud.com', school: 'ucf' },
  { email: '8qwq2zx8kj@privaterelay.appleid.com', school: 'ucf' },
  { email: 'anne.gamble@comcast.net', school: 'usc' },
  { email: 'leer3714@gmail.com', school: 'umd' },
  { email: '2twins@swbell.net', school: 'tulane' },
  { email: 'mgwerger@gmail.com', school: 'psu' },
  { email: 'robinfiddleposnack@gmail.com', school: 'tulane' },
  { email: 'mpeskoff@yahoo.com', school: 'fau' },
  { email: 'staceyrkaye@gmail.com', school: 'uga' },
  { email: 'alyssarukin1@gmail.com', school: 'osu' },
  { email: 'margostrahlberg@gmail.com', school: 'umd' },
  { email: 'fierceandsavvy@gmail.com', school: 'udel' },
  { email: 'jar8@cornell.edu', school: 'umd' },
  { email: 'blumecollegeconsulting@gmail.com', school: 'uga' },
  { email: 'adamm132@aol.com', school: 'fsu' },
  { email: 'gqqykz84js@privaterelay.appleid.com', school: 'tulane' },
  { email: 'aryn.lechtman@gmail.com', school: 'uga' },
  { email: 'lvkates@gmail.com', school: 'fsu' },
  { email: 'jodibenson27@gmail.com', school: 'jmu' },
  { email: 'gailswitsky@yahoo.com', school: 'tulane' },
  { email: 'padhi.usharani@gmail.com', school: 'psu' },
  { email: 'lkbrien@yahoo.com', school: 'tulane' },
  { email: 'anthony.sagardia@gmail.com', school: 'ucf' },
  { email: 'sweisleder@yahoo.com', school: 'osu' },
  { email: 'dinag374@icloud.com', school: 'fau' },
  { email: '2sv9kdhjjd@privaterelay.appleid.com', school: 'osu' },
  { email: 'theirvings@optonline.net', school: 'osu' },
  { email: 'phshfgbytc@privaterelay.appleid.com', school: 'fau' },
  { email: 'dena.duncan@verizon.net', school: 'udel' },
  { email: 'lfishman421@gmail.com', school: 'uky' },
  { email: 'kristen.arpaia@verizon.net', school: 'udel' },
  { email: 'lfish421@yahoo.com', school: 'jmu' },
  { email: 'suzannebakaletz@yahoo.com', school: 'psu' },
  { email: 'aimeemuth@gmail.com', school: 'osu' },
  { email: 'swapthebiz@gmail.com', school: 'osu' },
  { email: 'sabinanyc7@gmail.com', school: 'osu' },
  { email: 'bmmiklasz@gmail.com', school: 'osu' },
  { email: 'ilenehanin@gmail.com', school: 'umd' },
  { email: 'lounsberryn@slsd.org', school: 'psu' },
  { email: 'lynnabean@gmail.com', school: 'psu' },
  { email: 'matthewgarth@hotmail.com', school: 'osu' },
  { email: 'scottdkaplan@gmail.com', school: 'osu' },
  { email: 'scott@swapthebiz.com', school: 'osu' },
  { email: 'sfaktor@aol.com', school: 'osu' },
  { email: 'breezylear@hotmail.com', school: 'osu' },
  { email: 'g29jw5gnxr@privaterelay.appleid.com', school: 'osu' },
  { email: 'tstanco@gmail.com', school: 'osu' },
  { email: 'hodgsons@bbhcsd.org', school: 'osu' },
  { email: 'r88gk5hvdm@privaterelay.appleid.com', school: 'osu' },
  { email: 'shamila.imani@gmail.com', school: 'psu' },
  { email: 'jillhines40@gmail.com', school: 'ucf' },
  { email: 'jenkemp67@gmail.com', school: 'uga' },
  { email: 'mirasowens@gmail.com', school: 'uga' },
  { email: 'baottman@gmail.com', school: 'osu' },
  { email: 'amydavies1023@gmail.com', school: 'uga' },
  { email: 'theobeth@gmail.com', school: 'usc' },
  { email: 'amydryfuse@gmail.com', school: 'osu' },
  { email: 'janelle.dymond@gmail.com', school: 'osu' },
  { email: 'rembach8@gmail.com', school: 'osu' },
  { email: 'bernstein.stacy@gmail.com', school: 'uga' },
  { email: 'kyost2775@gmail.com', school: 'osu' },
  { email: 'robyn.walcoff@gmail.com', school: 'psu' },
  { email: 'echakere@hotmail.com', school: 'osu' },
  { email: 'allisonkgrossman4@icloud.com', school: 'osu' },
  { email: '96rx75tmg8@privaterelay.appleid.com', school: 'osu' },
  { email: 'xryps4qm6b@privaterelay.appleid.com', school: 'psu' },
  { email: 'goldeezgirl@me.com', school: 'osu' },
  { email: 'nikkimccabe79@gmail.com', school: 'uga' },
  { email: 'lynnsunset73@gmail.com', school: 'osu' },
  { email: 'beautycounterbydena@gmail.com', school: 'osu' },
  { email: 'okcardoso@gmail.com', school: 'ucf' },
  { email: 'kristenjsnow@gmail.com', school: 'osu' },
  { email: 'maevemooney21@gmail.com', school: 'osu' },
  { email: 'aglickman@corpspecla.com', school: 'osu' },
  { email: 'henrich.nat@gmail.com', school: 'osu' },
  { email: 'cq2g2xpg5z@privaterelay.appleid.com', school: 'osu' },
  { email: 'rachsilverman@aol.com', school: 'osu' },
  { email: 'imazzotti@mac.com', school: 'ucf' },
  { email: 'jdthgd@gmail.com', school: 'osu' },
  { email: 'lisagiegel3@gmail.com', school: 'osu' },
  { email: 'flyboats@gmail.com', school: 'ucf' },
  { email: 'alimalmad@gmail.com', school: 'osu' },
  { email: 'psn495sxpn@privaterelay.appleid.com', school: 'ucf' },
  { email: 'melissaconnealy@gmail.com', school: 'uga' },
  { email: 'erika.miller08@gmail.com', school: 'ucf' },
  { email: 'cinchg1@gmail.com', school: 'ucf' },
  { email: 'andrea.eckert@gmail.com', school: 'usc' },
  { email: 'kallianesis4@gmail.com', school: 'usc' },
  { email: 'cmjxrps5c4@privaterelay.appleid.com', school: 'uga' },
  { email: 'zmhjgwbw7n@privaterelay.appleid.com', school: 'uga' },
  { email: 'skoolmasterz@gmail.com', school: 'ucf' },
  { email: 'jenwalton1@gmail.com', school: 'ucf' },
  { email: 'niccor23@hotmail.com', school: 'ucf' },
  { email: 'lisakaestle1@gmail.com', school: 'udel' },
  { email: 'fkgk9spt5t@privaterelay.appleid.com', school: 'uga' },
  { email: 'jennpitera1@gmail.com', school: 'uga' },
  { email: 'ittap1@hotmail.com', school: 'uga' },
  { email: 'neddtorres@gmail.com', school: 'ucf' },
  { email: '58rdgd77gr@privaterelay.appleid.com', school: 'ucf' },
  { email: 'dewgrassmusic@gmail.com', school: 'ucf' },
  { email: 'caroline.burgess.cabrone@gmail.com', school: 'osu' },
  { email: 'tdj9td2x9q@privaterelay.appleid.com', school: 'uga' },
  { email: 'werbie28@verizon.net', school: 'ucf' },
  { email: 'lauren.pike2018@gmail.com', school: 'uga' },
  { email: 'juligarrett@gmail.com', school: 'uga' },
  { email: 'aligwyn@gmail.com', school: 'ucf' },
  { email: 'jodibossak@yahoo.com', school: 'uga' },
  { email: 'tiffanygleason@me.com', school: 'fau' },
  { email: 'cbackitis@gmail.com', school: 'ucf' },
  { email: 'carin0112@icloud.com', school: 'ucf' },
  { email: 'aespanatait@gmail.com', school: 'ucf' },
  { email: 'bridgetmduda@gmail.com', school: 'udel' },
  { email: 'kim.edelberg@outlook.com', school: 'fau' },
  { email: 'njoice@trschools.com', school: 'fau' },
  { email: 'mattinglyt4@gmail.com', school: 'fau' },
  { email: 'elissa.gruenberg@gmail.com', school: 'udel' },
  { email: 'juliannawalker15@gmail.com', school: 'ucf' },
  { email: 'sjwkhcq4xh@privaterelay.appleid.com', school: 'ucf' },
  { email: 'heatherbarca@gmail.com', school: 'udel' },
  { email: 'staceyjgarb@gmail.com', school: 'osu' },
  { email: 'wenaid815@gmail.com', school: 'ucf' },
  { email: 'cynthabaldino@gmail.com', school: 'udel' },
  { email: 'grillokidscollege@gmail.com', school: 'ucf' },
  { email: 'crkrqt26v4@privaterelay.appleid.com', school: 'ucf' },
  { email: 'maggieordona74@gmail.com', school: 'ucf' },
  { email: 'eweiwaters@gmail.com', school: 'ucf' },
  { email: 'sherrytramazzo@gmail.com', school: 'ucf' },
  { email: 'lightmanpa@yahoo.com', school: 'osu' },
  { email: 'goldenfamily416@gmail.com', school: 'ucf' },
  { email: 'sharon.stummer@northport.k12.ny.us', school: 'osu' },
  { email: 'kimberleewewing@gmail.com', school: 'ucf' },
  { email: 'kampjmz@gmail.com', school: 'ucf' },
  { email: 'bw57zjtzjg@privaterelay.appleid.com', school: 'ucf' },
  { email: 'y56qby546k@privaterelay.appleid.com', school: 'osu' },
  { email: 'gonzallaghers@verizon.net', school: 'ucf' },
  { email: 'sara.deborah.collins@gmail.com', school: 'udel' },
  { email: 'lwaller827@gmail.com', school: 'udel' },
  { email: 'debbie@nykravitz.com', school: 'osu' },
  { email: '8nzcd8hn55@privaterelay.appleid.com', school: 'usc' },
  { email: 'greene8600@gmail.com', school: 'usc' },
  { email: 'brittyw@me.com', school: 'osu' },
  { email: 'jlinnrubin@gmail.com', school: 'osu' },
  { email: 'q9gmrscjbx@privaterelay.appleid.com', school: 'osu' },
  { email: 'yphdtydv4z@privaterelay.appleid.com', school: 'osu' },
  { email: 'apeskin1217@gmail.com', school: 'osu' },
  { email: 'mjacovsky22@gmail.com', school: 'osu' },
  { email: 'robynrosen70@gmail.com', school: 'osu' },
  { email: 'msstrow@gmail.com', school: 'osu' },
  { email: 'zc4m6txfzg@privaterelay.appleid.com', school: 'osu' },
  { email: 'ksorgen@aol.com', school: 'osu' },
  { email: 'xvgpvvtw8n@privaterelay.appleid.com', school: 'fsu' },
  { email: 'heidimellison@gmail.com', school: 'usc' },
  { email: 'elisetedeschi@gmail.com', school: 'uga' },
  { email: 'mich.choz@gmail.com', school: 'osu' },
  { email: 'amysminchin@gmail.com', school: 'usc' },
  { email: 'mstetz76@gmail.com', school: 'usc' },
  { email: 'knoxlatonya7@gmail.com', school: 'usc' },
  { email: 'p9sfbgnky7@privaterelay.appleid.com', school: 'osu' },
  { email: '1runnergirl327@gmail.com', school: 'usc' },
  { email: 'wbmartin01@gmail.com', school: 'uga' },
  { email: 'lizasklar@hotmail.com', school: 'usc' },
  { email: 'rmjann@gmail.com', school: 'usc' },
  { email: 'rdobb@dobb.me', school: 'usc' },
  { email: 'munster7@gmail.com', school: 'tulane' },
  { email: 'gosinoff@gmail.com', school: 'usc' },
  { email: 'jhattersley%caringpeopleinc.com@gtempaccount.com', school: 'usc' },
  { email: 'brendanmattera@gmail.com', school: 'usc' },
  { email: 'marcymccabept@gmail.com', school: 'usc' },
  { email: 'kelli.dellinger@gmail.com', school: 'usc' },
  { email: 'shaun754@gmail.com', school: 'usc' },
  { email: 'kelly_email@yahoo.com', school: 'usc' },
  { email: 'mhawkins2830@gmail.com', school: 'usc' },
  { email: 'scoyne443@gmail.com', school: 'usc' },
  { email: 'macfarm100@gmail.com', school: 'usc' },
  { email: 'rebeccagadomski@gmail.com', school: 'usc' },
  { email: 'catherinebarbieri01@gmail.com', school: 'usc' },
  { email: 'candrewdds@yahoo.com', school: 'usc' },
  { email: 'apolek@nasd.k12.pa.us', school: 'usc' },
  { email: 'stephiec021876@gmail.com', school: 'osu' },
  { email: 'mackbrynn1313@gmail.com', school: 'usc' },
  { email: 'elisarroland@gmail.com', school: 'udel' },
  { email: 'rebecca.dawsonrn@gmail.com', school: 'usc' },
  { email: 'agalm@verizon.net', school: 'usc' },
  { email: 'janinelmclements@gmail.com', school: 'usc' },
  { email: 'jsniffen@gmail.com', school: 'usc' },
  { email: 'danagreci19@gmail.com', school: 'usc' },
  { email: 'theresam.elmer@gmail.com', school: 'usc' },
  { email: 'mlbelusic@yahoo.com', school: 'usc' },
  { email: 'nancy.jackson@gmail.com', school: 'usc' },
  { email: 'heathermorris2579@gmail.com', school: 'usc' },
  { email: 'jenprince23@gmail.com', school: 'usc' },
  { email: 'cmariepayne@gmail.com', school: 'usc' },
  { email: 'esroka@bwschools.net', school: 'osu' },
  { email: 'rachelsdf813@gmail.com', school: 'usc' },
  { email: 'krtship@gmail.com', school: 'usc' },
  { email: 'janelleshively@gmail.com', school: 'uga' },
  { email: 'deniserphillips@gmail.com', school: 'usc' },
  { email: 'alicia.halphen@gmail.com', school: 'osu' },
  { email: 'sandcanelas@gmail.com', school: 'usc' },
  { email: 'stevengold90@gmail.com', school: 'tulane' },
  { email: 'pamelasher10@gmail.com', school: 'usc' },
  { email: '4phillipharper@gmail.com', school: 'uga' },
  { email: 'mikebertolozzi@gmail.com', school: 'umd' },
  { email: 'jkcoopers@gmail.com', school: 'uga' },
  { email: 'burpoedj@gmail.com', school: 'uga' },
  { email: 'caryn11reid@gmail.com', school: 'uga' },
  { email: 'dina.shulman225@gmail.com', school: 'osu' },
  { email: 'pfeehan316@gmail.com', school: 'osu' },
  { email: 'pmaini@gmail.com', school: 'osu' },
  { email: 'soniasanjeev@gmail.com', school: 'osu' },
  { email: 'robynwolfe821@gmail.com', school: 'osu' },
  { email: 'catg355@gmail.com', school: 'usc' },
  { email: 'stephanie@delraytechnology.com', school: 'ucf' },
  { email: 'hswslp@gmail.com', school: 'usc' },
  { email: 'wbfm1129@gmail.com', school: 'udel' },
  { email: 'drdave1827@gmail.com', school: 'usc' },
  { email: 'anunair12@gmail.com', school: 'usc' },
  { email: 'karen.denton@cherokee1.org', school: 'usc' },
  { email: 'tmattera99@gmail.com', school: 'usc' },
  { email: 'ntbloom247@gmail.com', school: 'usc' },
  { email: 'ginamcguire5@gmail.com', school: 'usc' },
  { email: 'dmrichmond72@gmail.com', school: 'usc' },
  { email: 'katjay320@gmail.com', school: 'usc' },
  { email: 'bognermaria6@gmail.com', school: 'udel' },
  { email: 'carabharper@gmail.com', school: 'uga' },
  { email: 'karenmmurphy17@gmail.com', school: 'usc' },
  { email: 'jolenekorzeniewski@gmail.com', school: 'usc' },
  { email: 'sabotage1920@gmail.com', school: 'usc' },
  { email: 'sydneymgriffith@gmail.com', school: 'usc' },
  { email: 'ddsloane@gmail.com', school: 'usc' },
  { email: 'miknshan@me.com', school: 'usc' },
  { email: 'lawbarwick8@gmail.com', school: 'usc' },
  { email: 'taniahgerman@gmail.com', school: 'usc' },
  { email: 'taluyamx@gmail.com', school: 'usc' },
  { email: 'taralimoco@gmail.com', school: 'usc' },
  { email: 'kristin@davisaudiology.com', school: 'usc' },
  { email: 'pageamyd@gmail.com', school: 'usc' },
  { email: 'sisireia@gmail.com', school: 'usc' },
  { email: 'jennifer.r.mosser@gmail.com', school: 'usc' },
  { email: 'mhelf12@gmail.com', school: 'usc' },
  { email: 'adahlhauser4@gmail.com', school: 'usc' },
  { email: 'randisiegel08@gmail.com', school: 'usc' },
  { email: 'mrbrianmlevine@gmail.com', school: 'usc' },
  { email: 'sylvianola1970@gmail.com', school: 'usc' },
  { email: 'marisahhi@gmail.com', school: 'usc' },
  { email: 'kuulei0924@gmail.com', school: 'usc' },
  { email: 'artishort@gmail.com', school: 'usc' },
  { email: 'logsfb@verizon.net', school: 'usc' },
  { email: 'nickolai_30342@yahoo.com', school: 'usc' },
  { email: 'chloeloftis123@gmail.com', school: 'usc' },
  { email: 'thenley03@icloud.com', school: 'usc' },
  { email: 'danielle.rubenstein@gmail.com', school: 'usc' },
  { email: 'grdnjul@gmail.com', school: 'usc' },
  { email: 'dana.delavan@sumterschools.net', school: 'usc' },
  { email: 'adam@submersivemedia.com', school: 'usc' },
  { email: 'risa.mcgrew@gmail.com', school: 'usc' },
  { email: 'gillchiro9@gmail.com', school: 'usc' },
  { email: 'dpatten1524@gmail.com', school: 'usc' },
  { email: 'lasgesq@yahoo.com', school: 'usc' },
  { email: 'courtlandmthomas@gmail.com', school: 'usc' },
  { email: 'bgilmore924@gmail.com', school: 'usc' },
  { email: 'urotmt@gmail.com', school: 'usc' },
  { email: 'tejones404@gmail.com', school: 'usc' },
  { email: 'jillfields2@gmail.com', school: 'usc' },
  { email: 'allison.a.hallman@gmail.com', school: 'usc' },
  { email: 'jbazzone@gmail.com', school: 'usc' },
  { email: 'dj042103@gmail.com', school: 'usc' },
  { email: 'rachelawton@gmail.com', school: 'usc' },
  { email: 'wscottmacdonald1@gmail.com', school: 'usc' },
  { email: 'smorris127@gmail.com', school: 'usc' },
  { email: 'lauriebranum@gmail.com', school: 'usc' },
  { email: 'a.reardon@infantswim.com', school: 'usc' },
  { email: 'vlangermatt@gmail.com', school: 'usc' },
  { email: 'heidiryan71@gmail.com', school: 'udel' },
  { email: 'lakeil20@comcast.net', school: 'udel' },
  { email: 'mrsrobinbender@gmail.com', school: 'udel' },
  { email: 'mrshomedepot@gmail.com', school: 'udel' },
  { email: 'christineltate@gmail.com', school: 'usc' },
  { email: 'laurenwinter@hotmail.com', school: 'udel' },
  { email: 'lisablinder26@gmail.com', school: 'usc' },
  { email: 'kristine.mcgee@gmail.com', school: 'udel' },
  { email: 'loribrooks29@gmail.com', school: 'udel' },
  { email: 'dmcolontonio@gmail.com', school: 'usc' },
  { email: 'tsfeig@gmail.com', school: 'udel' },
  { email: 'lisagold38@yahoo.com', school: 'usc' },
  { email: 'janetlawson@optonline.net', school: 'usc' },
  { email: 'nicoge63@gmail.com', school: 'usc' },
  { email: 'jennven@comcast.net', school: 'usc' },
  { email: 'cgbrown976@gmail.com', school: 'usc' },
  { email: 'jennagoldblatt@gmail.com', school: 'usc' },
  { email: 'amysilverman1@gmail.com', school: 'usc' },
  { email: 'lefkodeb2@gmail.com', school: 'usc' },
  { email: 'cffosu@gmail.com', school: 'osu' },
  { email: 'jennafaye11u@gmail.com', school: 'usc' },
  { email: 'eurs16@gmail.com', school: 'usc' },
  { email: '14alyb@gmail.com', school: 'osu' },
  { email: 'jetwersky@gmail.com', school: 'udel' },
  { email: 'crystallease3@gmail.com', school: 'psu' },
  { email: 'cpaul72772@gmail.com', school: 'tulane' },
  { email: 'wyevoli@yahoo.com', school: 'tulane' },
  { email: 'lisareissman@gmail.com', school: 'tulane' },
  { email: 'lawbon222@gmail.com', school: 'psu' },
  { email: 'jodi@jodimurnick.com', school: 'usc' },
  { email: 'alyciakaufmanwright@gmail.com', school: 'psu' },
  { email: 'natalie@novawebgroup.com', school: 'psu' },
  { email: 'nancyrmartin4@gmail.com', school: 'miami' },
  { email: 'jarahwilk@gmail.com', school: 'osu' },
  { email: 'arleengoldenberg@gmail.com', school: 'fsu' },
  { email: 'loridubin2@gmail.com', school: 'osu' },
  { email: 'mlb379@gmail.com', school: 'ucf' },
  { email: 'jaime0525@gmail.com', school: 'umd' },
  { email: 'shillmant@bellsouth.net', school: 'miami' },
  { email: 'levinteam@gmail.com', school: 'psu' },
  { email: 'josinoff@gmail.com', school: 'usc' },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const dryRun = body.dryRun !== false; // default to dry run for safety
    const schoolFilter = body.schoolFilter || null; // e.g. 'ucf' to only do one school

    // Build email -> school map from CSV
    const emailToSchool = {};
    for (const row of CSV_DATA) {
      const email = row.email.toLowerCase().trim();
      // Skip UFL — those were already handled
      if (row.school !== 'ufl') {
        emailToSchool[email] = row.school;
      }
    }

    // Fetch all users
    const allUsers = await base44.asServiceRole.entities.User.list();

    const toUpdate = [];
    for (const u of (allUsers || [])) {
      const email = (u.email || '').toLowerCase().trim();
      const csvSchool = emailToSchool[email];
      if (!csvSchool) continue;
      if (schoolFilter && csvSchool !== schoolFilter) continue;

      // Only update if school_code doesn't already match
      if (u.school_code === csvSchool) continue;

      toUpdate.push({ id: u.id, email: u.email, currentSchool: u.school_code, newSchool: csvSchool });
    }

    if (dryRun) {
      const bySchool = {};
      for (const u of toUpdate) {
        bySchool[u.newSchool] = (bySchool[u.newSchool] || 0) + 1;
      }
      return Response.json({
        dryRun: true,
        total: toUpdate.length,
        bySchool,
        sample: toUpdate.slice(0, 20),
      });
    }

    // Apply updates with throttling
    let updated = 0;
    let errors = 0;
    for (const u of toUpdate) {
      try {
        await base44.asServiceRole.entities.User.update(u.id, {
          school_code: u.newSchool,
          school_name: SCHOOL_NAMES[u.newSchool] || u.newSchool,
          university: SCHOOL_NAMES[u.newSchool] || u.newSchool,
        });
        updated++;
        await new Promise(r => setTimeout(r, 100));
      } catch (err) {
        console.error(`Failed to update ${u.email}:`, err.message);
        errors++;
      }
    }

    return Response.json({ dryRun: false, updated, errors, total: toUpdate.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});