import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const SCHOOL_MAP = {
  'ufl':    { code: 'ufl',    name: 'University of Florida' },
  'udel':   { code: 'udel',   name: 'University of Delaware' },
  'umd':    { code: 'umd',    name: 'University of Maryland' },
  'umich':  { code: 'umich',  name: 'University of Michigan' },
  'tulane': { code: 'tulane', name: 'Tulane University' },
  'utexas': { code: 'utexas', name: 'University of Texas' },
  'ucf':    { code: 'ucf',    name: 'University of Central Florida' },
  'usc':    { code: 'usc',    name: 'University of Southern California' },
  'osu':    { code: 'osu',    name: 'Ohio State University' },
  'psu':    { code: 'psu',    name: 'Penn State University' },
  'fsu':    { code: 'fsu',    name: 'Florida State University' },
  'miami':  { code: 'miami',  name: 'University of Miami' },
  'uga':    { code: 'uga',    name: 'University of Georgia' },
  'fau':    { code: 'fau',    name: 'Florida Atlantic University' },
  'jmu':    { code: 'jmu',    name: 'James Madison University' },
  'uky':    { code: 'uky',    name: 'University of Kentucky' },
};

// CSV rows parsed from the file: [email, school_code]
// Only rows where school is non-empty and not 'ufl'
const CSV_DATA = [
  ["stwersky@udel.edu","udel"],
  ["leahdbloom@gmail.com","umd"],
  ["shell147@zoominternet.net","udel"],
  ["julialucci01@gmail.com","udel"],
  ["lisaromanlucci@gmail.com","udel"],
  ["charlotteposnack@gmail.com","utexas"],
  ["herzc@umich.edu","umich"],
  ["4gtpyhj2yt@privaterelay.appleid.com","udel"],
  ["franbloom13@gmail.com","umd"],
  ["mardochee.renaudin@gmail.com","ucf"],
  ["ljgarten@gmail.com","umich"],
  ["morganhurst29@gmail.com","umich"],
  ["amykates@optonline.net","umich"],
  ["bonnie.hurst@sbcglobal.net","umich"],
  ["abbyk6@yahoo.com","tulane"],
  ["ztqwpbst9f@privaterelay.appleid.com","umich"],
  ["matanmn@umich.edu","umich"],
  ["skushner10@gmail.com","umd"],
  ["sdnpy7sqf6@privaterelay.appleid.com","fau"],
  ["9z7bnm7n7j@privaterelay.appleid.com","fau"],
  ["carlymaass@gmail.com","psu"],
  ["llouwers@umich.edu","umich"],
  ["larchbol@yahoo.com","umich"],
  ["kapplauren@gmail.com","psu"],
  ["heidihdross@gmail.com","umd"],
  ["madstaylor168@gmail.com","udel"],
  ["tovi.taylor@gmail.com","udel"],
  ["mweyl25@gmail.com","udel"],
  ["spm0513@yahoo.com","usc"],
  ["brieeve@umich.edu","umich"],
  ["rhearam@umich.edu","umich"],
  ["robin.osswald@gmx.net","fau"],
  ["jill@uffastforward.com","usc"],
  ["jodi.leone@gmail.com","umich"],
  ["brian.dickstein1@gmail.com","umich"],
  ["stacey@campustocareer.net","uga"],
  ["jackhaberman693@gmail.com","umd"],
  ["marni@llpaint.com","umich"],
  ["ndtabs@verizon.net","umich"],
  ["jenolarsch@gmail.com","umich"],
  ["zachary.zimmerman@cantor.com","umich"],
  ["barrifruitbine@gmail.com","utexas"],
  ["tfhertwig@msn.com","psu"],
  ["tkollinsmith@gmail.com","umich"],
  ["bport@umich.edu","umich"],
  ["charnasfamily5@gmail.com","umich"],
  ["hopespiller@gmail.com","umich"],
  ["blain.aleah@gmail.com","ucf"],
  ["selenamarievk@gmail.com","umich"],
  ["jilevine@optonline.net","umich"],
  ["ethan@gloudon.com","umich"],
  ["mayolfamily@bellsouth.net","umich"],
  ["nuglou@gmail.com","umich"],
  ["lsimkuspaskola@gmail.com","umich"],
  ["hillary523@icloud.com","umich"],
  ["alyssa@allaboutadmissions.com","umich"],
  ["stalburg@gmail.com","umich"],
  ["ericayaker@binghamcounseling.com","umich"],
  ["tarynschaffer@gmail.com","umich"],
  ["debsimp@optonline.net","osu"],
  ["h49v2pttkf@privaterelay.appleid.com","umich"],
  ["bfein@umich.edu","umich"],
  ["lorijrosen@gmail.com","umich"],
  ["goldy3b24@gmail.com","osu"],
  ["bonniekatz38@aol.com","umich"],
  ["dibeerman@hotmail.com","umich"],
  ["jdheimowitz@bellsouth.net","umich"],
  ["mattlevin1111@gmail.com","umich"],
  ["sallygainesmoorhead@gmail.com","umich"],
  ["ppardes1026@gmail.com","umich"],
  ["carynfitzgerald8@gmail.com","umich"],
  ["rachelstahler@gmail.com","umich"],
  ["tjnaugh14@gmail.com","umich"],
  ["zr40544@uga.edu","uga"],
  ["sivin@optonline.net","umich"],
  ["sbeshears0129@gmail.com","fau"],
  ["fk72vrck99@privaterelay.appleid.com","fau"],
  ["simpkins02@yahoo.com","usc"],
  ["dahliatop@gmail.com","umd"],
  ["eachance1@gmail.com","ucf"],
  ["jacobhnovick0830@icloud.com","fau"],
  ["mjb26311@uga.edu","uga"],
  ["barib1207@yahoo.com","fsu"],
  ["kimedel@gmail.com","fsu"],
  ["michellerbrady@hotmail.com","ucf"],
  ["buibaogianguyen2008@gmail.com","ucf"],
  ["amandabrown05@yahoo.com","ucf"],
  ["miguel.sanchezm2002@gmail.com","ucf"],
  ["collegefastforward.untimely030@passfwd.com","ucf"],
  ["schristenson@aerospace-policy.org","ucf"],
  ["woodamandaa@gmail.com","ucf"],
  ["mcampbell1@bellsouth.net","ucf"],
  ["adrucker1@tulane.edu","tulane"],
  ["judeambrose@icloud.com","ucf"],
  ["nickfontaine.jupiter@yahoo.com","ucf"],
  ["8qwq2zx8kj@privaterelay.appleid.com","ucf"],
  ["andrewbenson1120@gmail.com","jmu"],
  ["anne.gamble@comcast.net","usc"],
  ["leer3714@gmail.com","umd"],
  ["2twins@swbell.net","tulane"],
  ["brooks.1337@buckeyemail.osu.edu","osu"],
  ["paul.1140@osu.edu","osu"],
  ["mgwerger@gmail.com","psu"],
  ["robinfiddleposnack@gmail.com","tulane"],
  ["michaelderosa2025@gmail.com","psu"],
  ["mpeskoff@yahoo.com","fau"],
  ["staceyrkaye@gmail.com","uga"],
  ["caterukin@gmail.com","osu"],
  ["alyssarukin1@gmail.com","osu"],
  ["jonah.strahlberg@gmail.com","umd"],
  ["margostrahlberg@gmail.com","umd"],
  ["fierceandsavvy@gmail.com","udel"],
  ["jar8@cornell.edu","umd"],
  ["blumecollegeconsulting@gmail.com","uga"],
  ["gqqykz84js@privaterelay.appleid.com","tulane"],
  ["aryn.lechtman@gmail.com","uga"],
  ["lvkates@gmail.com","fsu"],
  ["jodibenson27@gmail.com","jmu"],
  ["zgoodman@terpmail.umd.edu","umd"],
  ["gailswitsky@yahoo.com","tulane"],
  ["deanlichtenfeld@gmail.com","psu"],
  ["padhi.usharani@gmail.com","psu"],
  ["lkbrien@yahoo.com","tulane"],
  ["costa@milopaper.com","osu"],
  ["mseigh2024@fau.edu","fau"],
  ["annawise1227@gmail.com","osu"],
  ["anthony.sagardia@gmail.com","ucf"],
  ["palombo.21@osu.edu","osu"],
  ["sweisleder@yahoo.com","osu"],
  ["sedelberg17@gmail.com","fau"],
  ["dinag374@icloud.com","fau"],
  ["2sv9kdhjjd@privaterelay.appleid.com","osu"],
  ["theirvings@optonline.net","osu"],
  ["zyr23209@uga.edu","uga"],
  ["majoralegend906@gmail.com","ucf"],
  ["phshfgbytc@privaterelay.appleid.com","fau"],
  ["dena.duncan@verizon.net","udel"],
  ["lfishman421@gmail.com","uky"],
  ["sidmail31@gmail.com","osu"],
  ["kristen.arpaia@verizon.net","udel"],
  ["jackpinney11@gmail.com","osu"],
  ["suzannebakaletz@yahoo.com","psu"],
  ["aimeemuth@gmail.com","osu"],
  ["2wqx5474hf@privaterelay.appleid.com","osu"],
  ["swapthebiz@gmail.com","osu"],
  ["sabinanyc7@gmail.com","osu"],
  ["cmvanish@gmail.com","osu"],
  ["bmmiklasz@gmail.com","osu"],
  ["livlounsberry@gmail.com","psu"],
  ["ilenehanin@gmail.com","umd"],
  ["lounsberryn@slsd.org","psu"],
  ["lynnabean@gmail.com","psu"],
  ["matthewgarth@hotmail.com","osu"],
  ["scottdkaplan@gmail.com","osu"],
  ["scott@swapthebiz.com","osu"],
  ["sfaktor@aol.com","osu"],
  ["breezylear@hotmail.com","osu"],
  ["wbd81213@uga.edu","uga"],
  ["g29jw5gnxr@privaterelay.appleid.com","osu"],
  ["ryandavies0222@gmail.com","uga"],
  ["9gd78p5vw9@privaterelay.appleid.com","osu"],
  ["tstanco@gmail.com","osu"],
  ["hodgsons@bbhcsd.org","osu"],
  ["r88gk5hvdm@privaterelay.appleid.com","osu"],
  ["shamila.imani@gmail.com","psu"],
  ["jillhines40@gmail.com","ucf"],
  ["jenkemp67@gmail.com","uga"],
  ["mirasowens@gmail.com","uga"],
  ["baottman@gmail.com","osu"],
  ["amydavies1023@gmail.com","uga"],
  ["ryanbaxterpw@gmail.com","uga"],
  ["andrea.eckert@gmail.com","usc"],
  ["ryan@ryancchurchill22@gmail.com","uga"],
  ["ryancchurchill22@gmail.com","uga"],
  ["lucastpitera@gmail.com","uga"],
  ["rmd15234@uga.edu","uga"],
  ["kallianesis4@gmail.com","usc"],
  ["lukerosenthal18@gmail.com","osu"],
  ["cmjxrps5c4@privaterelay.appleid.com","uga"],
  ["zmhjgwbw7n@privaterelay.appleid.com","uga"],
  ["skoolmasterz@gmail.com","ucf"],
  ["jenwalton1@gmail.com","ucf"],
  ["jakejunek@gmail.com","ucf"],
  ["niccor23@hotmail.com","ucf"],
  ["bcgrubb08@hotmail.com","ucf"],
  ["lisakaestle1@gmail.com","udel"],
  ["fkgk9spt5t@privaterelay.appleid.com","uga"],
  ["jennpitera1@gmail.com","uga"],
  ["ittap1@hotmail.com","uga"],
  ["neddtorres@gmail.com","ucf"],
  ["58rdgd77gr@privaterelay.appleid.com","ucf"],
  ["gjesailor1@gmail.com","ucf"],
  ["aligwyn@gmail.com","ucf"],
  ["jodibossak@yahoo.com","uga"],
  ["tiffanygleason@me.com","fau"],
  ["cbackitis@gmail.com","ucf"],
  ["blakeh0215@gmail.com","ucf"],
  ["carin0112@icloud.com","ucf"],
  ["aespanatait@gmail.com","ucf"],
  ["bridgetmduda@gmail.com","udel"],
  ["kim.edelberg@outlook.com","fau"],
  ["njoice@trschools.com","fau"],
  ["mattinglyt4@gmail.com","fau"],
  ["elissa.gruenberg@gmail.com","udel"],
  ["juliannawalker15@gmail.com","ucf"],
  ["sjwkhcq4xh@privaterelay.appleid.com","ucf"],
  ["heatherbarca@gmail.com","udel"],
  ["alexaoriel530@gmail.com","tulane"],
  ["davidljerome03@gmail.com","ucf"],
  ["kitanbanjo@yahoo.com","ucf"],
  ["staceyjgarb@gmail.com","osu"],
  ["wenaid815@gmail.com","ucf"],
  ["cynthabaldino@gmail.com","udel"],
  ["bheitzner2025@fau.edu","fau"],
  ["grillokidscollege@gmail.com","ucf"],
  ["crkrqt26v4@privaterelay.appleid.com","ucf"],
  ["maggieordona74@gmail.com","ucf"],
  ["m99y2p2479@privaterelay.appleid.com","ucf"],
  ["eweiwaters@gmail.com","ucf"],
  ["sherrytramazzo@gmail.com","ucf"],
  ["lightmanpa@yahoo.com","osu"],
  ["goldenfamily416@gmail.com","ucf"],
  ["sharon.stummer@northport.k12.ny.us","osu"],
  ["kimberleewewing@gmail.com","ucf"],
  ["kampjmz@gmail.com","ucf"],
  ["bw57zjtzjg@privaterelay.appleid.com","ucf"],
  ["y56qby546k@privaterelay.appleid.com","osu"],
  ["gonzallaghers@verizon.net","ucf"],
  ["sara.deborah.collins@gmail.com","udel"],
  ["alissa.arnaldo@gmail.com","osu"],
  ["lwaller827@gmail.com","udel"],
  ["debbie@nykravitz.com","osu"],
  ["8nzcd8hn55@privaterelay.appleid.com","usc"],
  ["nathanillouz@gmail.com","osu"],
  ["greene8600@gmail.com","usc"],
  ["bridgetpolek@icloud.com","usc"],
  ["brittyw@me.com","osu"],
  ["jlinnrubin@gmail.com","osu"],
  ["98cpbp725b@privaterelay.appleid.com","osu"],
  ["papaveronico@gmail.com","osu"],
  ["q9gmrscjbx@privaterelay.appleid.com","osu"],
  ["yphdtydv4z@privaterelay.appleid.com","osu"],
  ["joeymace27@gmail.com","osu"],
  ["tjgrobman@gmail.com","osu"],
  ["ing876@gmail.com","osu"],
  ["apeskin1217@gmail.com","osu"],
  ["mjacovsky22@gmail.com","osu"],
  ["samrosen6@gmail.com","osu"],
  ["sophiabunn@optonline.net","osu"],
  ["robynrosen70@gmail.com","osu"],
  ["msstrow@gmail.com","osu"],
  ["zc4m6txfzg@privaterelay.appleid.com","osu"],
  ["ksorgen@aol.com","osu"],
  ["jesserosen3@gmail.com","osu"],
  ["rj84wqg8sd@privaterelay.appleid.com","osu"],
  ["xvgpvvtw8n@privaterelay.appleid.com","fsu"],
  ["heidimellison@gmail.com","usc"],
  ["htgdxh5k9z@privaterelay.appleid.com","fsu"],
  ["elise.tedeschi@gmail.com","uga"],
  ["mich.choz@gmail.com","osu"],
  ["amysminchin@gmail.com","usc"],
  ["mstetz76@gmail.com","usc"],
  ["aj06popov@aol.com","osu"],
  ["knoxlatonya7@gmail.com","usc"],
  ["p9sfbgnky7@privaterelay.appleid.com","osu"],
  ["jab46967@uga.edu","uga"],
  ["1runnergirl327@gmail.com","usc"],
  ["blake.martin@gmail.com","uga"],
  ["wbmartin01@gmail.com","uga"],
  ["lizasklar@hotmail.com","usc"],
  ["rmjann@gmail.com","usc"],
  ["rdobb@dobb.me","usc"],
  ["munster7@gmail.com","tulane"],
  ["gosinoff@gmail.com","usc"],
  ["jhattersley%caringpeopleinc.com@gtempaccount.com","usc"],
  ["brendanmattera@gmail.com","usc"],
  ["marcymccabept@gmail.com","usc"],
  ["kelli.dellinger@gmail.com","usc"],
  ["shaun754@gmail.com","usc"],
  ["pascuzzi@email.sc.edu","usc"],
  ["kelly_email@yahoo.com","usc"],
  ["mhawkins2830@gmail.com","usc"],
  ["scoyne443@gmail.com","usc"],
  ["macfarm100@gmail.com","usc"],
  ["rebeccagadomski@gmail.com","usc"],
  ["catherinebarbieri01@gmail.com","usc"],
  ["candrewdds@yahoo.com","usc"],
  ["apolek@nasd.k12.pa.us","usc"],
  ["mackbrynn1313@gmail.com","usc"],
  ["elisarroland@gmail.com","udel"],
  ["rebecca.dawsonrn@gmail.com","usc"],
  ["kgmccabe@udel.edu","udel"],
  ["agalm@verizon.net","usc"],
  ["janinelmclements@gmail.com","usc"],
  ["jsniffen@gmail.com","usc"],
  ["danagreci19@gmail.com","usc"],
  ["theresam.elmer@gmail.com","usc"],
  ["mlbelusic@yahoo.com","usc"],
  ["nancy.jackson@gmail.com","usc"],
  ["heathermorris2579@gmail.com","usc"],
  ["jenprince23@gmail.com","usc"],
  ["cmariepayne@gmail.com","usc"],
  ["esroka@bwschools.net","osu"],
  ["rachelsdf813@gmail.com","usc"],
  ["krtship@gmail.com","usc"],
  ["janelleshively@gmail.com","uga"],
  ["deniserphillips@gmail.com","usc"],
  ["alicia.halphen@gmail.com","osu"],
  ["sandcanelas@gmail.com","usc"],
  ["stevengold90@gmail.com","tulane"],
  ["pamelasher10@gmail.com","usc"],
  ["4phillipharper@gmail.com","uga"],
  ["mikebertolozzi@gmail.com","umd"],
  ["jkcoopers@gmail.com","uga"],
  ["burpoedj@gmail.com","uga"],
  ["caryn11reid@gmail.com","uga"],
  ["dina.shulman225@gmail.com","osu"],
  ["pfeehan316@gmail.com","osu"],
  ["pmaini@gmail.com","osu"],
  ["tjmenkes@gmail.com","usc"],
  ["sjm309@miami.edu","miami"],
  ["catg355@gmail.com","usc"],
  ["aidenlimoco@gmail.com","osu"],
  ["stephanie@delraytechnology.com","ucf"],
  ["hswslp@gmail.com","usc"],
  ["wbfm1129@gmail.com","udel"],
  ["drdave1827@gmail.com","usc"],
  ["anunair12@gmail.com","usc"],
  ["karen.denton@cherokee1.org","usc"],
  ["tmattera99@gmail.com","usc"],
  ["ntbloom247@gmail.com","usc"],
  ["ginamcguire5@gmail.com","usc"],
  ["dmrichmond72@gmail.com","usc"],
  ["katjay320@gmail.com","usc"],
  ["mbogner@udel.edu","udel"],
  ["angis105@gmail.com","udel"],
  ["bognermaria6@gmail.com","udel"],
  ["carabharper@gmail.com","uga"],
  ["karenmmurphy17@gmail.com","usc"],
  ["jolenekorzeniewski@gmail.com","usc"],
  ["sabotage1920@gmail.com","usc"],
  ["jd127@email.sc.edu","usc"],
  ["sydneymgriffith@gmail.com","usc"],
  ["ddsloane@gmail.com","usc"],
  ["miknshan@me.com","usc"],
  ["lawbarwick8@gmail.com","usc"],
  ["migueln@email.sc.edu","usc"],
  ["taniahgerman@gmail.com","usc"],
  ["taluyamx@gmail.com","usc"],
  ["taralimoco@gmail.com","usc"],
  ["kristin@davisaudiology.com","usc"],
  ["pageamyd@gmail.com","usc"],
  ["sisireia@gmail.com","usc"],
  ["jennifer.r.mosser@gmail.com","usc"],
  ["mhelf12@gmail.com","usc"],
  ["adahlhauser4@gmail.com","usc"],
  ["randisiegel08@gmail.com","usc"],
  ["mrbrianmlevine@gmail.com","usc"],
  ["sylvianola1970@gmail.com","usc"],
  ["marisahhi@gmail.com","usc"],
  ["kuulei0924@gmail.com","usc"],
  ["artishort@gmail.com","usc"],
  ["logsfb@verizon.net","usc"],
  ["nickolai_30342@yahoo.com","usc"],
  ["chloeloftis123@gmail.com","usc"],
  ["thenley03@icloud.com","usc"],
  ["danielle.rubenstein@gmail.com","usc"],
  ["idonotdriveaminivan@gmail.com","usc"],
  ["grdnjul@gmail.com","usc"],
  ["dana.delavan@sumterschools.net","usc"],
  ["adam@submersivemedia.com","usc"],
  ["risa.mcgrew@gmail.com","usc"],
  ["gillchiro9@gmail.com","usc"],
  ["dpatten1524@gmail.com","usc"],
  ["emmielampy@gmail.com","usc"],
  ["lasgesq@yahoo.com","usc"],
  ["cameronxs0822@gmail.com","usc"],
  ["courtlandmthomas@gmail.com","usc"],
  ["bgilmore924@gmail.com","usc"],
  ["urotmt@gmail.com","usc"],
  ["tejones404@gmail.com","usc"],
  ["haileyfields523@gmail.com","usc"],
  ["jillfields2@gmail.com","usc"],
  ["allison.a.hallman@gmail.com","usc"],
  ["jbazzone@gmail.com","usc"],
  ["dj042103@gmail.com","usc"],
  ["rachelawton@gmail.com","usc"],
  ["hagoodvann@gmail.com","usc"],
  ["wscottmacdonald1@gmail.com","usc"],
  ["scottymac3104@gmail.com","usc"],
  ["ty.pole15@gmail.com","usc"],
  ["smorris127@gmail.com","usc"],
  ["lauriebranum@gmail.com","usc"],
  ["a.reardon@infantswim.com","usc"],
  ["vlangermatt@gmail.com","usc"],
  ["heidi.ryan@gmail.com","udel"],
  ["lakeil20@comcast.net","udel"],
  ["mcgintyk@email.sc.edu","usc"],
  ["jrcalhou@udel.edu","udel"],
  ["mrsrobinbender@gmail.com","udel"],
  ["mrshomedepot@gmail.com","udel"],
  ["christineltate@gmail.com","usc"],
  ["colturnpaugh@gmail.com","usc"],
  ["laurenwinter@hotmail.com","udel"],
  ["lisablinder26@gmail.com","usc"],
  ["dylanfrancis.carter@gmail.com","usc"],
  ["kristine.mcgee@gmail.com","udel"],
  ["loribrooks29@gmail.com","udel"],
  ["dmcolontonio@gmail.com","usc"],
  ["tsfeig@gmail.com","udel"],
  ["lisagold38@yahoo.com","usc"],
  ["janetlawson@optonline.net","usc"],
  ["nicoge63@gmail.com","usc"],
  ["brgold1022@gmail.com","usc"],
  ["jennven@comcast.net","usc"],
  ["samanthab4505@gmail.com","usc"],
  ["gugfamily88@gmail.com","usc"],
  ["madarake07@gmail.com","usc"],
  ["desimone.ava@gmail.com","usc"],
  ["cgbrown976@gmail.com","usc"],
  ["jennagoldblatt@gmail.com","usc"],
  ["amysilverman1@gmail.com","usc"],
  ["lefkodeb2@gmail.com","usc"],
  ["loloteaches@hotmail.com","usc"],
  ["cffosu@gmail.com","osu"],
  ["jennafaye11u@gmail.com","usc"],
  ["eurs16@gmail.com","usc"],
  ["14alyb@gmail.com","osu"],
  ["jetwersky@gmail.com","udel"],
  ["crystallease3@gmail.com","psu"],
  ["cpaul72772@gmail.com","tulane"],
  ["wyevoli@yahoo.com","tulane"],
  ["lisareissman@gmail.com","tulane"],
  ["lawbon222@gmail.com","psu"],
  ["jodi@jodimurnick.com","usc"],
  ["jennild22@gmail.com","osu"],
  ["alyciakaufmanwright@gmail.com","psu"],
  ["natalie@novawebgroup.com","psu"],
  ["alexjrose31@gmail.com","psu"],
  ["nancyrmartin4@gmail.com","miami"],
  ["jarahwilk@gmail.com","osu"],
  ["arleengoldenberg@gmail.com","fsu"],
  ["loridubin2@gmail.com","osu"],
  ["mlb379@gmail.com","ucf"],
  ["jaime0525@gmail.com","umd"],
  ["shillmant@bellsouth.net","miami"],
  ["levinteam@gmail.com","psu"],
  ["josinoff@gmail.com","usc"],
  ["ilanamsharon@gmail.com","udel"],
  ["elise.tedeschi@gmail.com","uga"],
  ["adamm132@aol.com","fsu"],
  ["lfish421@yahoo.com","jmu"],
  ["heidiryan71@gmail.com","udel"],
  ["lfishman421@gmail.com","uky"],
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const dryRun = body.dryRun !== false; // default to dry run

    // Filter to only non-ufl entries
    const toProcess = CSV_DATA.filter(([, school]) => school && school !== 'ufl');

    // Group by school for summary
    const schoolCounts = {};
    for (const [, school] of toProcess) {
      schoolCounts[school] = (schoolCounts[school] || 0) + 1;
    }

    if (dryRun) {
      return Response.json({
        dryRun: true,
        totalToProcess: toProcess.length,
        bySchool: schoolCounts,
        message: 'Dry run complete. Pass dryRun: false to apply changes.'
      });
    }

    // Fetch all users and build email->id map in memory
    console.log('Fetching all users...');
    const allUsers = await base44.asServiceRole.entities.User.list('-created_date', 2000);
    const emailToUser = {};
    for (const u of (allUsers || [])) {
      if (u.email) emailToUser[u.email.toLowerCase()] = u;
    }
    console.log(`Loaded ${Object.keys(emailToUser).length} users into memory map`);

    // Process in batches to avoid timeouts
    const offset = body.offset || 0;
    const batchSize = body.batchSize || 60;
    const batch = toProcess.slice(offset, offset + batchSize);
    const results = { updated: [], notFound: [], errors: [] };

    for (const [email, schoolCode] of batch) {
      const schoolInfo = SCHOOL_MAP[schoolCode];
      if (!schoolInfo) {
        results.errors.push({ email, reason: `Unknown school code: ${schoolCode}` });
        continue;
      }

      const u = emailToUser[email.toLowerCase()];
      if (!u) {
        results.notFound.push(email);
        continue;
      }

      await base44.asServiceRole.entities.User.update(u.id, {
        school_code: schoolInfo.code,
        school_name: schoolInfo.name,
        university: schoolInfo.name,
      });
      results.updated.push({ email, school_code: schoolInfo.code, school_name: schoolInfo.name });
      
      // Small delay to avoid rate limits
      await new Promise(r => setTimeout(r, 80));
    }

    const nextOffset = offset + batchSize;
    const done = nextOffset >= toProcess.length;

    return Response.json({
      dryRun: false,
      offset,
      batchSize,
      batchProcessed: batch.length,
      updated: results.updated.length,
      notFound: results.notFound.length,
      errors: results.errors.length,
      notFoundList: results.notFound,
      errorList: results.errors,
      done,
      nextOffset: done ? null : nextOffset,
      remaining: Math.max(0, toProcess.length - nextOffset),
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});