import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

/**
 * Bulk invite users from the CSV export into the database.
 * Uses base44.users.inviteUser to create accounts.
 * 
 * Call with:
 *   { dryRun: true }  — to preview what would be imported
 *   { dryRun: false, offset: 0, batchSize: 20 }  — to actually import a batch
 *   { dryRun: false, offset: 20, batchSize: 20 } — next batch, etc.
 * 
 * Optional: { schoolFilter: 'ucf' } to only import one school
 */

const SCHOOL_NAMES = {
  ucf: 'University of Central Florida',
  ufl: 'University of Florida',
  fsu: 'Florida State University',
  fau: 'Florida Atlantic University',
  usf: 'University of South Florida',
  usc: 'University of Southern California',
  umich: 'University of Michigan',
  osu: 'Ohio State University',
  psu: 'Penn State University',
  umd: 'University of Maryland',
  udel: 'University of Delaware',
  uga: 'University of Georgia',
  tulane: 'Tulane University',
  uky: 'University of Kentucky',
  jmu: 'James Madison University',
  utexas: 'University of Texas',
  miami: 'University of Miami',
};

// Full CSV data parsed (email, school, persona, full_name)
const CSV_USERS = [
  { email: 'shell147@zoominternet.net', school: 'udel', persona: 'parent', full_name: 'shell147' },
  { email: 'lisaromanlucci@gmail.com', school: 'udel', persona: 'parent', full_name: 'Lisa Lucci' },
  { email: '4gtpyhj2yt@privaterelay.appleid.com', school: 'udel', persona: 'parent', full_name: '' },
  { email: 'franbloom13@gmail.com', school: 'umd', persona: 'parent', full_name: 'Francine Bloom' },
  { email: 'mardochee.renaudin@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'Mardochee Renaudin' },
  { email: 'ljgarten@gmail.com', school: 'umich', persona: 'parent', full_name: 'Lisa Garten' },
  { email: 'morganhurst29@gmail.com', school: 'umich', persona: 'alumni', full_name: 'morganhurst29' },
  { email: 'amykates@optonline.net', school: 'umich', persona: 'parent', full_name: 'amykates' },
  { email: 'bonnie.hurst@sbcglobal.net', school: 'umich', persona: 'alumni', full_name: 'bonnie.hurst' },
  { email: 'ztqwpbst9f@privaterelay.appleid.com', school: 'umich', persona: 'parent', full_name: '' },
  { email: '9z7bnm7n7j@privaterelay.appleid.com', school: 'fau', persona: 'parent', full_name: '' },
  { email: 'carlymaass@gmail.com', school: 'psu', persona: 'parent', full_name: 'carly maass' },
  { email: 'larchbol@yahoo.com', school: 'umich', persona: 'parent', full_name: 'larchbol' },
  { email: 'kapplauren@gmail.com', school: 'psu', persona: 'parent', full_name: 'Lauren Kapp' },
  { email: 'heidihdross@gmail.com', school: 'umd', persona: 'parent', full_name: 'Dross Heidi' },
  { email: 'tovi.taylor@gmail.com', school: 'udel', persona: 'parent', full_name: 'Tovi Taylor' },
  { email: 'mweyl25@gmail.com', school: 'udel', persona: 'parent', full_name: 'mweyl25' },
  { email: 'jill@uffastforward.com', school: 'usc', persona: 'parent', full_name: 'Jill Osinoff' },
  { email: 'jodi.leone@gmail.com', school: 'umich', persona: 'alumni', full_name: 'Jodi Leone' },
  { email: 'brian.dickstein1@gmail.com', school: 'umich', persona: 'alumni', full_name: 'brian.dickstein1' },
  { email: 'marni@llpaint.com', school: 'umich', persona: 'alumni', full_name: 'marni' },
  { email: 'ndtabs@verizon.net', school: 'umich', persona: 'parent', full_name: 'nancy tabs' },
  { email: 'jenolarsch@gmail.com', school: 'umich', persona: 'alumni', full_name: 'Jen Olarsch' },
  { email: 'zachary.zimmerman@cantor.com', school: 'umich', persona: 'alumni', full_name: 'zachary.zimmerman' },
  { email: 'barrifruitbine@gmail.com', school: 'utexas', persona: 'parent', full_name: 'barrifruitbine' },
  { email: 'tfhertwig@msn.com', school: 'psu', persona: 'parent', full_name: 'tfhertwig' },
  { email: 'tkollinsmith@gmail.com', school: 'umich', persona: 'alumni', full_name: 'Tracy Smith' },
  { email: 'charnasfamily5@gmail.com', school: 'umich', persona: 'alumni', full_name: 'charnasfamily5' },
  { email: 'hopespiller@gmail.com', school: 'umich', persona: 'parent', full_name: 'hopespiller' },
  { email: 'blain.aleah@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'Aleah Blain' },
  { email: 'selenamarievk@gmail.com', school: 'umich', persona: 'parent', full_name: 'Selena Van Klompenberg' },
  { email: 'jilevine@optonline.net', school: 'umich', persona: 'parent', full_name: 'jilevine' },
  { email: 'mayolfamily@bellsouth.net', school: 'umich', persona: 'parent', full_name: 'mayolfamily' },
  { email: 'nuglou@gmail.com', school: 'umich', persona: 'parent', full_name: 'K L' },
  { email: 'lsimkuspaskola@gmail.com', school: 'umich', persona: 'parent', full_name: 'Lukas' },
  { email: 'hillary523@icloud.com', school: 'umich', persona: 'parent', full_name: 'hillary523' },
  { email: 'alyssa@allaboutadmissions.com', school: 'umich', persona: 'parent', full_name: 'Alyssa Endelman' },
  { email: 'stalburg@gmail.com', school: 'umich', persona: 'parent', full_name: 'Barbi Stalburg Kasoff' },
  { email: 'ericayaker@binghamcounseling.com', school: 'umich', persona: 'parent', full_name: '' },
  { email: 'tarynschaffer@gmail.com', school: 'umich', persona: 'parent', full_name: 'Taryn Schaffer' },
  { email: 'debsimp@optonline.net', school: 'osu', persona: 'parent', full_name: 'debsimp' },
  { email: 'h49v2pttkf@privaterelay.appleid.com', school: 'umich', persona: 'parent', full_name: '' },
  { email: 'lorijrosen@gmail.com', school: 'umich', persona: 'parent', full_name: 'lorijrosen' },
  { email: 'goldy3b24@gmail.com', school: 'osu', persona: 'parent', full_name: 'Bryan Goldman' },
  { email: 'bonniekatz38@aol.com', school: 'umich', persona: 'alumni', full_name: 'bonniekatz38' },
  { email: 'dibeerman@hotmail.com', school: 'umich', persona: 'parent', full_name: 'dibeerman' },
  { email: 'jdheimowitz@bellsouth.net', school: 'umich', persona: 'parent', full_name: 'jdheimowitz' },
  { email: 'mattlevin1111@gmail.com', school: 'umich', persona: 'alumni', full_name: 'Matt Levin' },
  { email: 'sallygainesmoorhead@gmail.com', school: 'umich', persona: 'parent', full_name: 'sallygainesmoorhead' },
  { email: 'ppardes1026@gmail.com', school: 'umich', persona: 'parent', full_name: 'Pamela Pardes' },
  { email: 'carynfitzgerald8@gmail.com', school: 'umich', persona: 'parent', full_name: 'Caryn Fitzgerald' },
  { email: 'rachelstahler@gmail.com', school: 'umich', persona: 'parent', full_name: 'rachelstahler' },
  { email: 'tjnaugh14@gmail.com', school: 'umich', persona: 'alumni', full_name: 'Tom Naughton' },
  { email: 'sivin@optonline.net', school: 'umich', persona: 'parent', full_name: 'sivin' },
  { email: 'fk72vrck99@privaterelay.appleid.com', school: 'fau', persona: 'parent', full_name: '' },
  { email: 'simpkins02@yahoo.com', school: 'usc', persona: 'parent', full_name: 'simpkins02' },
  { email: 'dahliatop@gmail.com', school: 'umd', persona: 'parent', full_name: 'Dahlia Topolosky' },
  { email: 'eachance1@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'eachance1' },
  { email: 'kimedel@gmail.com', school: 'fsu', persona: 'parent', full_name: 'kimedel' },
  { email: 'michellerbrady@hotmail.com', school: 'ucf', persona: 'parent', full_name: 'michellerbrady' },
  { email: 'amandabrown05@yahoo.com', school: 'ucf', persona: 'alumni', full_name: 'amandabrown05' },
  { email: 'miguel.sanchezm2002@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'Miguel Sanchez' },
  { email: 'collegefastforward.untimely030@passfwd.com', school: 'ucf', persona: 'alumni', full_name: 'collegefastforward.untimely030' },
  { email: 'schristenson@aerospace-policy.org', school: 'ucf', persona: 'parent', full_name: 'Shawna Christenson' },
  { email: 'woodamandaa@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'amanda wood' },
  { email: 'mcampbell1@bellsouth.net', school: 'ucf', persona: 'parent', full_name: 'Monica' },
  { email: 'judeambrose@icloud.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: '8qwq2zx8kj@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'anne.gamble@comcast.net', school: 'usc', persona: 'parent', full_name: 'anne.gamble' },
  { email: 'leer3714@gmail.com', school: 'umd', persona: 'parent', full_name: 'Adrienne Bransky' },
  { email: '2twins@swbell.net', school: 'tulane', persona: 'parent', full_name: '2twins' },
  { email: 'mgwerger@gmail.com', school: 'psu', persona: 'parent', full_name: 'mgwerger' },
  { email: 'robinfiddleposnack@gmail.com', school: 'tulane', persona: 'parent', full_name: 'Robin Fiddle Posnack' },
  { email: 'mpeskoff@yahoo.com', school: 'fau', persona: 'parent', full_name: 'mpeskoff' },
  { email: 'staceyrkaye@gmail.com', school: 'uga', persona: 'parent', full_name: 'staceyrkaye' },
  { email: 'alyssarukin1@gmail.com', school: 'osu', persona: 'parent', full_name: 'alyssarukin1' },
  { email: 'margostrahlberg@gmail.com', school: 'umd', persona: 'parent', full_name: 'Margo Strahlberg' },
  { email: 'fierceandsavvy@gmail.com', school: 'udel', persona: 'parent', full_name: 'Jill Sharon' },
  { email: 'jar8@cornell.edu', school: 'umd', persona: 'parent', full_name: 'jar8' },
  { email: 'blumecollegeconsulting@gmail.com', school: 'uga', persona: 'parent', full_name: 'Debbie Blume' },
  { email: 'adamm132@aol.com', school: 'fsu', persona: 'alumni', full_name: 'adamm132' },
  { email: 'gqqykz84js@privaterelay.appleid.com', school: 'tulane', persona: 'parent', full_name: '' },
  { email: 'aryn.lechtman@gmail.com', school: 'uga', persona: 'parent', full_name: 'Aryn Lechtman' },
  { email: 'lvkates@gmail.com', school: 'fsu', persona: 'parent', full_name: 'lvkates' },
  { email: 'jodibenson27@gmail.com', school: 'jmu', persona: 'parent', full_name: 'jodi benson' },
  { email: 'gailswitsky@yahoo.com', school: 'tulane', persona: 'parent', full_name: 'gailswitsky' },
  { email: 'padhi.usharani@gmail.com', school: 'psu', persona: 'parent', full_name: 'Usha Padhi' },
  { email: 'lkbrien@yahoo.com', school: 'tulane', persona: 'alumni', full_name: 'lkbrien' },
  { email: 'anthony.sagardia@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'Anthony Sagardia' },
  { email: 'sweisleder@yahoo.com', school: 'osu', persona: 'parent', full_name: 'sweisleder' },
  { email: 'dinag374@icloud.com', school: 'fau', persona: 'parent', full_name: 'Dina G' },
  { email: '2sv9kdhjjd@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'theirvings@optonline.net', school: 'osu', persona: 'parent', full_name: 'theirvings' },
  { email: 'phshfgbytc@privaterelay.appleid.com', school: 'fau', persona: 'parent', full_name: '' },
  { email: 'dena.duncan@verizon.net', school: 'udel', persona: 'parent', full_name: 'Dena Duncan' },
  { email: 'lfishman421@gmail.com', school: 'uky', persona: 'parent', full_name: 'lfishman421' },
  { email: 'kristen.arpaia@verizon.net', school: 'udel', persona: 'parent', full_name: 'kristen.arpaia' },
  { email: 'lfish421@yahoo.com', school: 'jmu', persona: 'parent', full_name: 'lfish421' },
  { email: 'suzannebakaletz@yahoo.com', school: 'psu', persona: 'parent', full_name: 'suzannebakaletz' },
  { email: 'aimeemuth@gmail.com', school: 'osu', persona: 'parent', full_name: 'aimee muth' },
  { email: 'swapthebiz@gmail.com', school: 'osu', persona: 'parent', full_name: 'Scott Eisenberg' },
  { email: 'sabinanyc7@gmail.com', school: 'osu', persona: 'parent', full_name: 'Sabina Fishkin' },
  { email: 'bmmiklasz@gmail.com', school: 'osu', persona: 'parent', full_name: 'Brenda Miklasz' },
  { email: 'ilenehanin@gmail.com', school: 'umd', persona: 'parent', full_name: 'iris h' },
  { email: 'lounsberryn@slsd.org', school: 'psu', persona: 'parent', full_name: 'Nicole Lounsberry' },
  { email: 'lynnabean@gmail.com', school: 'psu', persona: 'parent', full_name: 'lynnabean@gmail.com' },
  { email: 'matthewgarth@hotmail.com', school: 'osu', persona: 'parent', full_name: 'matthewgarth' },
  { email: 'scottdkaplan@gmail.com', school: 'osu', persona: 'parent', full_name: 'scottdkaplan' },
  { email: 'scott@swapthebiz.com', school: 'osu', persona: 'parent', full_name: 'Scott Eisenberg' },
  { email: 'sfaktor@aol.com', school: 'osu', persona: 'parent', full_name: 'sfaktor' },
  { email: 'breezylear@hotmail.com', school: 'osu', persona: 'parent', full_name: 'breezylear' },
  { email: 'g29jw5gnxr@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'tstanco@gmail.com', school: 'osu', persona: 'parent', full_name: 'Teresa Stanco' },
  { email: 'hodgsons@bbhcsd.org', school: 'osu', persona: 'parent', full_name: 'Shari Hodgson' },
  { email: 'r88gk5hvdm@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'shamila.imani@gmail.com', school: 'psu', persona: 'parent', full_name: 'Shamila Imani' },
  { email: 'jillhines40@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Jill Hines' },
  { email: 'jenkemp67@gmail.com', school: 'uga', persona: 'parent', full_name: 'Jenny Kemp' },
  { email: 'mirasowens@gmail.com', school: 'uga', persona: 'parent', full_name: 'Mira Owens' },
  { email: 'baottman@gmail.com', school: 'osu', persona: 'parent', full_name: 'Barbara Ottman' },
  { email: 'amydavies1023@gmail.com', school: 'uga', persona: 'parent', full_name: 'Amy Davies' },
  { email: 'theobeth@gmail.com', school: 'usc', persona: 'parent', full_name: 'Elizabeth McCrea Theodore' },
  { email: 'amydryfuse@gmail.com', school: 'osu', persona: 'parent', full_name: 'Amy Dryfuse' },
  { email: 'janelle.dymond@gmail.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'rembach8@gmail.com', school: 'osu', persona: 'parent', full_name: 'Renee Kalmbach' },
  { email: 'bernstein.stacy@gmail.com', school: 'uga', persona: 'parent', full_name: 'Stacy Bernstein' },
  { email: 'kyost2775@gmail.com', school: 'osu', persona: 'parent', full_name: 'Kristin Yost' },
  { email: 'robyn.walcoff@gmail.com', school: 'psu', persona: 'parent', full_name: 'Robyn Walcoff' },
  { email: 'echakere@hotmail.com', school: 'osu', persona: 'parent', full_name: 'Christina Kerekes' },
  { email: 'allisonkgrossman4@icloud.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: '96rx75tmg8@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'xryps4qm6b@privaterelay.appleid.com', school: 'psu', persona: 'parent', full_name: '' },
  { email: 'goldeezgirl@me.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'nikkimccabe79@gmail.com', school: 'uga', persona: 'parent', full_name: 'Nicole McCabe' },
  { email: 'lynnsunset73@gmail.com', school: 'osu', persona: 'parent', full_name: 'lynn sunset' },
  { email: 'beautycounterbydena@gmail.com', school: 'osu', persona: 'parent', full_name: 'Dena Astrin' },
  { email: 'okcardoso@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Kristin Cardoso' },
  { email: 'kristenjsnow@gmail.com', school: 'osu', persona: 'parent', full_name: 'Kristen Snow' },
  { email: 'maevemooney21@gmail.com', school: 'osu', persona: 'alumni', full_name: 'Maeve Mooney' },
  { email: 'aglickman@corpspecla.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'henrich.nat@gmail.com', school: 'osu', persona: 'parent', full_name: 'Natalie Henrich' },
  { email: 'cq2g2xpg5z@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'rachsilverman@aol.com', school: 'osu', persona: 'parent', full_name: 'Rachael Silverman' },
  { email: 'imazzotti@mac.com', school: 'ucf', persona: 'alumni', full_name: '' },
  { email: 'jdthgd@gmail.com', school: 'osu', persona: 'parent', full_name: 'Judy Good' },
  { email: 'lisagiegel3@gmail.com', school: 'osu', persona: 'parent', full_name: 'Lisa Giegel' },
  { email: 'flyboats@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Tyler & Lynn Blake' },
  { email: 'alimalmad@gmail.com', school: 'osu', persona: 'parent', full_name: 'Allison Bohm Malmad' },
  { email: 'psn495sxpn@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'melissaconnealy@gmail.com', school: 'uga', persona: 'alumni', full_name: 'Melissa Connealy' },
  { email: 'erika.miller08@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Erika Miller' },
  { email: 'cinchg1@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Cindy Chong' },
  { email: 'andrea.eckert@gmail.com', school: 'usc', persona: 'parent', full_name: 'Andrea Eckert' },
  { email: 'kallianesis4@gmail.com', school: 'usc', persona: 'parent', full_name: 'premonc' },
  { email: 'cmjxrps5c4@privaterelay.appleid.com', school: 'uga', persona: 'parent', full_name: '' },
  { email: 'zmhjgwbw7n@privaterelay.appleid.com', school: 'uga', persona: 'parent', full_name: '' },
  { email: 'skoolmasterz@gmail.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'jenwalton1@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Jen W' },
  { email: 'niccor23@hotmail.com', school: 'ucf', persona: 'parent', full_name: 'N Junek' },
  { email: 'lisakaestle1@gmail.com', school: 'udel', persona: 'parent', full_name: 'Lisa Kaestle' },
  { email: 'fkgk9spt5t@privaterelay.appleid.com', school: 'uga', persona: 'parent', full_name: '' },
  { email: 'jennpitera1@gmail.com', school: 'uga', persona: 'parent', full_name: 'Jenn Pitera' },
  { email: 'ittap1@hotmail.com', school: 'uga', persona: 'parent', full_name: 'patti daniel' },
  { email: 'neddtorres@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Jason Torres' },
  { email: '58rdgd77gr@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'dewgrassmusic@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Kerry Dew' },
  { email: 'caroline.burgess.cabrone@gmail.com', school: 'osu', persona: 'parent', full_name: 'Caroline Burgess' },
  { email: 'tdj9td2x9q@privaterelay.appleid.com', school: 'uga', persona: 'parent', full_name: '' },
  { email: 'werbie28@verizon.net', school: 'ucf', persona: 'parent', full_name: 'Heather Werb' },
  { email: 'lauren.pike2018@gmail.com', school: 'uga', persona: 'alumni', full_name: 'Lauren Pike' },
  { email: 'juligarrett@gmail.com', school: 'uga', persona: 'parent', full_name: 'Julie Garrett' },
  { email: 'aligwyn@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Alice and Gwyn' },
  { email: 'jodibossak@yahoo.com', school: 'uga', persona: 'parent', full_name: '' },
  { email: 'tiffanygleason@me.com', school: 'fau', persona: 'parent', full_name: '' },
  { email: 'cbackitis@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Carla Backitis' },
  { email: 'carin0112@icloud.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'aespanatait@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Amanda Espana-Tait' },
  { email: 'bridgetmduda@gmail.com', school: 'udel', persona: 'parent', full_name: 'Bridget Duda' },
  { email: 'kim.edelberg@outlook.com', school: 'fau', persona: 'parent', full_name: 'Kim Edelberg' },
  { email: 'njoice@trschools.com', school: 'fau', persona: 'parent', full_name: 'Nicole Joice' },
  { email: 'mattinglyt4@gmail.com', school: 'fau', persona: 'parent', full_name: 'Terry Mattingly' },
  { email: 'elissa.gruenberg@gmail.com', school: 'udel', persona: 'parent', full_name: 'Elissa Gruenberg' },
  { email: 'juliannawalker15@gmail.com', school: 'ucf', persona: 'alumni', full_name: 'Julianna Walker (Jay)' },
  { email: 'sjwkhcq4xh@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'heatherbarca@gmail.com', school: 'udel', persona: 'parent', full_name: 'Heather Barca' },
  { email: 'staceyjgarb@gmail.com', school: 'osu', persona: 'parent', full_name: 'Stacey garb' },
  { email: 'wenaid815@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Diane Kemper' },
  { email: 'cynthabaldino@gmail.com', school: 'udel', persona: 'parent', full_name: 'Cynthia Baldino' },
  { email: 'grillokidscollege@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Esther Grillo' },
  { email: 'crkrqt26v4@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'maggieordona74@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Maggie Ordona' },
  { email: 'eweiwaters@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Waters' },
  { email: 'sherrytramazzo@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Sherry Tramazzo' },
  { email: 'lightmanpa@yahoo.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'goldenfamily416@gmail.com', school: 'ucf', persona: 'parent', full_name: 'christy golden' },
  { email: 'sharon.stummer@northport.k12.ny.us', school: 'osu', persona: 'parent', full_name: 'Sharon Stummer' },
  { email: 'kimberleewewing@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Kimberlee Ewing' },
  { email: 'kampjmz@gmail.com', school: 'ucf', persona: 'parent', full_name: 'JMZ Kamphuis' },
  { email: 'bw57zjtzjg@privaterelay.appleid.com', school: 'ucf', persona: 'parent', full_name: '' },
  { email: 'y56qby546k@privaterelay.appleid.com', school: 'osu', persona: 'alumni', full_name: '' },
  { email: 'gonzallaghers@verizon.net', school: 'ucf', persona: 'parent', full_name: 'Lyngo Nzalez' },
  { email: 'sara.deborah.collins@gmail.com', school: 'udel', persona: 'parent', full_name: 'Sara Collins' },
  { email: 'lwaller827@gmail.com', school: 'udel', persona: 'parent', full_name: 'L A Waller' },
  { email: 'debbie@nykravitz.com', school: 'osu', persona: 'parent', full_name: 'Debbie Kravitz' },
  { email: '8nzcd8hn55@privaterelay.appleid.com', school: 'usc', persona: 'parent', full_name: '' },
  { email: 'greene8600@gmail.com', school: 'usc', persona: 'parent', full_name: '' },
  { email: 'brittyw@me.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'jlinnrubin@gmail.com', school: 'osu', persona: 'parent', full_name: 'Jennifer Rubin' },
  { email: 'q9gmrscjbx@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'yphdtydv4z@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'apeskin1217@gmail.com', school: 'osu', persona: 'parent', full_name: 'Audr Peskin' },
  { email: 'mjacovsky22@gmail.com', school: 'osu', persona: 'alumni', full_name: 'Matt Jacovsky' },
  { email: 'robynrosen70@gmail.com', school: 'osu', persona: 'parent', full_name: 'Robyn Rosen' },
  { email: 'msstrow@gmail.com', school: 'osu', persona: 'parent', full_name: 'Jen S' },
  { email: 'zc4m6txfzg@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'ksorgen@aol.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: 'xvgpvvtw8n@privaterelay.appleid.com', school: 'fsu', persona: 'parent', full_name: '' },
  { email: 'heidimellison@gmail.com', school: 'usc', persona: 'parent', full_name: 'Heidi Mellison (Realtor)' },
  { email: 'elisetedeschi@gmail.com', school: 'uga', persona: 'parent', full_name: 'Elise Tedeschi' },
  { email: 'mich.choz@gmail.com', school: 'osu', persona: 'parent', full_name: 'Michelle Chozahinoff' },
  { email: 'amysminchin@gmail.com', school: 'usc', persona: 'parent', full_name: 'Amy Minchin' },
  { email: 'mstetz76@gmail.com', school: 'usc', persona: 'parent', full_name: 'Melanie Stetz' },
  { email: 'knoxlatonya7@gmail.com', school: 'usc', persona: 'parent', full_name: 'LaTonya Charise' },
  { email: 'p9sfbgnky7@privaterelay.appleid.com', school: 'osu', persona: 'parent', full_name: '' },
  { email: '1runnergirl327@gmail.com', school: 'usc', persona: 'parent', full_name: 'Katherine Hoenig' },
  { email: 'wbmartin01@gmail.com', school: 'uga', persona: 'parent', full_name: 'Blake Martin' },
  { email: 'lizasklar@hotmail.com', school: 'usc', persona: 'parent', full_name: 'LIZASKLAR@HOTMAIL.COM' },
  { email: 'rmjann@gmail.com', school: 'usc', persona: 'parent', full_name: 'Renée Jannuzzi' },
  { email: 'rdobb@dobb.me', school: 'usc', persona: 'parent', full_name: 'Ryan Dobb' },
  { email: 'munster7@gmail.com', school: 'tulane', persona: 'alumni', full_name: 'Paley Munn' },
  { email: 'gosinoff@gmail.com', school: 'usc', persona: 'parent', full_name: 'Greg Osinoff' },
  { email: 'brendanmattera@gmail.com', school: 'usc', persona: 'alumni', full_name: 'B' },
  { email: 'marcymccabept@gmail.com', school: 'usc', persona: 'parent', full_name: 'Marcy McCabe' },
  { email: 'kelli.dellinger@gmail.com', school: 'usc', persona: 'parent', full_name: 'Kelli Dellinger' },
  { email: 'shaun754@gmail.com', school: 'usc', persona: 'parent', full_name: 'Shaun Washington' },
  { email: 'kelly_email@yahoo.com', school: 'usc', persona: 'parent', full_name: 'kelly_email@yahoo.com' },
  { email: 'mhawkins2830@gmail.com', school: 'usc', persona: 'parent', full_name: 'Michelle Hawkins' },
  { email: 'scoyne443@gmail.com', school: 'usc', persona: 'parent', full_name: 'Scott Coyne' },
  { email: 'macfarm100@gmail.com', school: 'usc', persona: 'parent', full_name: 'Angeli Macdonald' },
  { email: 'rebeccagadomski@gmail.com', school: 'usc', persona: 'parent', full_name: 'Rebecca Gadomski' },
  { email: 'catherinebarbieri01@gmail.com', school: 'usc', persona: 'parent', full_name: 'Catherine Barbieri' },
  { email: 'candrewdds@yahoo.com', school: 'usc', persona: 'parent', full_name: 'Andrew Snell' },
  { email: 'apolek@nasd.k12.pa.us', school: 'usc', persona: 'parent', full_name: 'Alison Polek' },
  { email: 'stephiec021876@gmail.com', school: 'osu', persona: 'parent', full_name: 'Stephanie Cramer' },
  { email: 'mackbrynn1313@gmail.com', school: 'usc', persona: 'parent', full_name: 'Teresa Badalamenti' },
  { email: 'elisarroland@gmail.com', school: 'udel', persona: 'parent', full_name: 'Elisa Roland' },
  { email: 'rebecca.dawsonrn@gmail.com', school: 'usc', persona: 'parent', full_name: 'Rebecca Dawson' },
  { email: 'agalm@verizon.net', school: 'usc', persona: 'parent', full_name: 'Amanda Galm' },
  { email: 'janinelmclements@gmail.com', school: 'usc', persona: 'parent', full_name: 'Janine Clements' },
  { email: 'jsniffen@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jennifer Sniffen' },
  { email: 'danagreci19@gmail.com', school: 'usc', persona: 'parent', full_name: 'Dana Greci' },
  { email: 'theresam.elmer@gmail.com', school: 'usc', persona: 'parent', full_name: 'Theresa Elmer' },
  { email: 'mlbelusic@yahoo.com', school: 'usc', persona: 'parent', full_name: 'Melisa Skific' },
  { email: 'nancy.jackson@gmail.com', school: 'usc', persona: 'parent', full_name: 'Nancy Jackson' },
  { email: 'heathermorris2579@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Heather Morris' },
  { email: 'jenprince23@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jennifer Prince' },
  { email: 'cmariepayne@gmail.com', school: 'usc', persona: 'parent', full_name: 'Christine Payne' },
  { email: 'esroka@bwschools.net', school: 'osu', persona: 'parent', full_name: 'Erin Sroka' },
  { email: 'rachelsdf813@gmail.com', school: 'usc', persona: 'parent', full_name: 'Rachel Fortune' },
  { email: 'krtship@gmail.com', school: 'usc', persona: 'parent', full_name: 'k topinka' },
  { email: 'janelleshively@gmail.com', school: 'uga', persona: 'parent', full_name: 'Janelle Shively' },
  { email: 'deniserphillips@gmail.com', school: 'usc', persona: 'parent', full_name: 'Denise Phillips' },
  { email: 'alicia.halphen@gmail.com', school: 'osu', persona: 'parent', full_name: 'Alicia Halphen' },
  { email: 'sandcanelas@gmail.com', school: 'usc', persona: 'parent', full_name: 'Sandra Canelas' },
  { email: 'stevengold90@gmail.com', school: 'tulane', persona: 'alumni', full_name: 'Steven Goldberg' },
  { email: 'pamelasher10@gmail.com', school: 'usc', persona: 'parent', full_name: 'Pam Sher' },
  { email: '4phillipharper@gmail.com', school: 'uga', persona: 'parent', full_name: 'Phillip Harper' },
  { email: 'mikebertolozzi@gmail.com', school: 'umd', persona: 'parent', full_name: 'Mike Bertolozzi' },
  { email: 'jkcoopers@gmail.com', school: 'uga', persona: 'parent', full_name: 'John and Kimberly Cooper' },
  { email: 'burpoedj@gmail.com', school: 'uga', persona: 'parent', full_name: 'Duane Burpoe' },
  { email: 'caryn11reid@gmail.com', school: 'uga', persona: 'parent', full_name: 'Caryn Reid' },
  { email: 'dina.shulman225@gmail.com', school: 'osu', persona: 'parent', full_name: 'Dina Shulman' },
  { email: 'pfeehan316@gmail.com', school: 'osu', persona: 'parent', full_name: 'Patricia Feehan' },
  { email: 'pmaini@gmail.com', school: 'osu', persona: 'parent', full_name: 'Prachi Nagpal' },
  { email: 'soniasanjeev@gmail.com', school: 'osu', persona: 'parent', full_name: 'Sonia Sanjeev' },
  { email: 'robynwolfe821@gmail.com', school: 'osu', persona: 'parent', full_name: 'Robyn Wolfe' },
  { email: 'catg355@gmail.com', school: 'usc', persona: 'parent', full_name: 'Catherine Anderson' },
  { email: 'stephanie@delraytechnology.com', school: 'ucf', persona: 'parent', full_name: 'Stephanie Budin' },
  { email: 'hswslp@gmail.com', school: 'usc', persona: 'parent', full_name: 'Heather Williams' },
  { email: 'wbfm1129@gmail.com', school: 'udel', persona: 'parent', full_name: 'Wendy M.' },
  { email: 'drdave1827@gmail.com', school: 'usc', persona: 'parent', full_name: 'David Fields' },
  { email: 'anunair12@gmail.com', school: 'usc', persona: 'parent', full_name: 'ANURADHA NAIR' },
  { email: 'karen.denton@cherokee1.org', school: 'usc', persona: 'parent', full_name: 'KAREN DENTON' },
  { email: 'tmattera99@gmail.com', school: 'usc', persona: 'parent', full_name: 'Tara Mattera' },
  { email: 'ntbloom247@gmail.com', school: 'usc', persona: 'parent', full_name: 'Nina Bloomingburg' },
  { email: 'ginamcguire5@gmail.com', school: 'usc', persona: 'parent', full_name: 'gina mcguire' },
  { email: 'dmrichmond72@gmail.com', school: 'usc', persona: 'parent', full_name: 'Dawn Richmond' },
  { email: 'katjay320@gmail.com', school: 'usc', persona: 'parent', full_name: 'Kathleen Jeffcoat' },
  { email: 'bognermaria6@gmail.com', school: 'udel', persona: 'parent', full_name: 'Maria Bogner' },
  { email: 'carabharper@gmail.com', school: 'uga', persona: 'parent', full_name: 'Cara Harper' },
  { email: 'karenmmurphy17@gmail.com', school: 'usc', persona: 'parent', full_name: 'Karen Murphy' },
  { email: 'jolenekorzeniewski@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jolene Korzeniewski' },
  { email: 'sabotage1920@gmail.com', school: 'usc', persona: 'parent', full_name: 'Crystal Goodwin' },
  { email: 'sydneymgriffith@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Sydney Griffith' },
  { email: 'ddsloane@gmail.com', school: 'usc', persona: 'parent', full_name: 'D Ryan' },
  { email: 'miknshan@me.com', school: 'usc', persona: 'parent', full_name: 'Shannon Mourar' },
  { email: 'lawbarwick8@gmail.com', school: 'usc', persona: 'parent', full_name: 'Lori B' },
  { email: 'taniahgerman@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Taniah German' },
  { email: 'taluyamx@gmail.com', school: 'usc', persona: 'parent', full_name: 'Martha Leticia De Leon Rodriguez' },
  { email: 'taralimoco@gmail.com', school: 'usc', persona: 'parent', full_name: 'Tara Limoco' },
  { email: 'kristin@davisaudiology.com', school: 'usc', persona: 'parent', full_name: 'Kristin Davis' },
  { email: 'pageamyd@gmail.com', school: 'usc', persona: 'parent', full_name: 'Amy Page' },
  { email: 'sisireia@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Sisireia Simmons' },
  { email: 'jennifer.r.mosser@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jennifer Mosser' },
  { email: 'mhelf12@gmail.com', school: 'usc', persona: 'parent', full_name: 'Mitch Helfman' },
  { email: 'adahlhauser4@gmail.com', school: 'usc', persona: 'parent', full_name: 'April Dahlhauser' },
  { email: 'randisiegel08@gmail.com', school: 'usc', persona: 'parent', full_name: 'Randi Siegel' },
  { email: 'mrbrianmlevine@gmail.com', school: 'usc', persona: 'parent', full_name: 'Brian Levine' },
  { email: 'sylvianola1970@gmail.com', school: 'usc', persona: 'parent', full_name: 'Sylvia Brown' },
  { email: 'marisahhi@gmail.com', school: 'usc', persona: 'parent', full_name: 'Marisa Wagner' },
  { email: 'kuulei0924@gmail.com', school: 'usc', persona: 'parent', full_name: 'Wendy Early' },
  { email: 'artishort@gmail.com', school: 'usc', persona: 'parent', full_name: 'arti short' },
  { email: 'logsfb@verizon.net', school: 'usc', persona: 'parent', full_name: 'JB' },
  { email: 'nickolai_30342@yahoo.com', school: 'usc', persona: 'parent', full_name: 'Nicole Scarborough' },
  { email: 'chloeloftis123@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Chloe' },
  { email: 'thenley03@icloud.com', school: 'usc', persona: 'alumni', full_name: 'Taylor Henley' },
  { email: 'danielle.rubenstein@gmail.com', school: 'usc', persona: 'parent', full_name: 'Danielle Rubenstein' },
  { email: 'grdnjul@gmail.com', school: 'usc', persona: 'parent', full_name: 'Julie Houston' },
  { email: 'dana.delavan@sumterschools.net', school: 'usc', persona: 'alumni', full_name: 'Dana DeLavan' },
  { email: 'adam@submersivemedia.com', school: 'usc', persona: 'parent', full_name: 'Adam Spielberger' },
  { email: 'risa.mcgrew@gmail.com', school: 'usc', persona: 'parent', full_name: 'Risa McGrew' },
  { email: 'gillchiro9@gmail.com', school: 'usc', persona: 'parent', full_name: 'lauren g' },
  { email: 'dpatten1524@gmail.com', school: 'usc', persona: 'parent', full_name: 'Donna Patten' },
  { email: 'lasgesq@yahoo.com', school: 'usc', persona: 'parent', full_name: 'lasgesq@yahoo.com' },
  { email: 'courtlandmthomas@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Courtland Thomas' },
  { email: 'bgilmore924@gmail.com', school: 'usc', persona: 'parent', full_name: 'Brandy Gilmore' },
  { email: 'urotmt@gmail.com', school: 'usc', persona: 'parent', full_name: 'Tricia Thaker' },
  { email: 'tejones404@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Thomas Jones' },
  { email: 'jillfields2@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jill Fields' },
  { email: 'allison.a.hallman@gmail.com', school: 'usc', persona: 'parent', full_name: 'Allison Hallman' },
  { email: 'jbazzone@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jill Bazzone' },
  { email: 'dj042103@gmail.com', school: 'usc', persona: 'parent', full_name: 'D Hollars' },
  { email: 'rachelawton@gmail.com', school: 'usc', persona: 'parent', full_name: 'Rochelle' },
  { email: 'wscottmacdonald1@gmail.com', school: 'usc', persona: 'parent', full_name: 'W. Scott MacDonald' },
  { email: 'smorris127@gmail.com', school: 'usc', persona: 'parent', full_name: 'Samantha Morris' },
  { email: 'lauriebranum@gmail.com', school: 'usc', persona: 'parent', full_name: 'Laurie BRANUM' },
  { email: 'a.reardon@infantswim.com', school: 'usc', persona: 'parent', full_name: 'Amy Reardon' },
  { email: 'vlangermatt@gmail.com', school: 'usc', persona: 'parent', full_name: 'Veronica Langer' },
  { email: 'heidiryan71@gmail.com', school: 'udel', persona: 'parent', full_name: 'Heidi Ryan' },
  { email: 'lakeil20@comcast.net', school: 'udel', persona: 'alumni', full_name: 'Lisa Cartwright' },
  { email: 'mrsrobinbender@gmail.com', school: 'udel', persona: 'parent', full_name: 'Robin Bender' },
  { email: 'mrshomedepot@gmail.com', school: 'udel', persona: 'parent', full_name: 'Alana Rodriguez' },
  { email: 'christineltate@gmail.com', school: 'usc', persona: 'parent', full_name: 'Christine Tate' },
  { email: 'laurenwinter@hotmail.com', school: 'udel', persona: 'alumni', full_name: 'Lauren' },
  { email: 'lisablinder26@gmail.com', school: 'usc', persona: 'parent', full_name: 'Lisa Rogers' },
  { email: 'kristine.mcgee@gmail.com', school: 'udel', persona: 'parent', full_name: 'Kristine McGee' },
  { email: 'loribrooks29@gmail.com', school: 'udel', persona: 'parent', full_name: 'Lori Brooks' },
  { email: 'dmcolontonio@gmail.com', school: 'usc', persona: 'parent', full_name: 'Dawn Miller' },
  { email: 'tsfeig@gmail.com', school: 'udel', persona: 'alumni', full_name: 'Tara Feig' },
  { email: 'lisagold38@yahoo.com', school: 'usc', persona: 'parent', full_name: 'lisagold38@yahoo.com' },
  { email: 'janetlawson@optonline.net', school: 'usc', persona: 'parent', full_name: 'Janet' },
  { email: 'nicoge63@gmail.com', school: 'usc', persona: 'parent', full_name: 'alexandra felsenhardt' },
  { email: 'jennven@comcast.net', school: 'usc', persona: 'parent', full_name: 'Jen Venditti' },
  { email: 'cgbrown976@gmail.com', school: 'usc', persona: 'parent', full_name: 'Casey Brown' },
  { email: 'jennagoldblatt@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jenna Goldblatt' },
  { email: 'amysilverman1@gmail.com', school: 'usc', persona: 'parent', full_name: 'Amy Silverman' },
  { email: 'lefkodeb2@gmail.com', school: 'usc', persona: 'parent', full_name: 'D Cohen' },
  { email: 'cffosu@gmail.com', school: 'osu', persona: 'parent', full_name: 'Brandon Schops' },
  { email: 'jennafaye11u@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Jenna Ursaner' },
  { email: 'eurs16@gmail.com', school: 'usc', persona: 'alumni', full_name: 'Evan Ursaner' },
  { email: '14alyb@gmail.com', school: 'osu', persona: 'parent', full_name: 'Alyson Brooks' },
  { email: 'jetwersky@gmail.com', school: 'udel', persona: 'parent', full_name: 'Jamie Twersky' },
  { email: 'crystallease3@gmail.com', school: 'psu', persona: 'parent', full_name: 'Crystal Lease' },
  { email: 'cpaul72772@gmail.com', school: 'tulane', persona: 'alumni', full_name: 'Colette Paul' },
  { email: 'wyevoli@yahoo.com', school: 'tulane', persona: 'alumni', full_name: 'Wendy' },
  { email: 'lisareissman@gmail.com', school: 'tulane', persona: 'alumni', full_name: 'Lisa Reissman' },
  { email: 'lawbon222@gmail.com', school: 'psu', persona: 'parent', full_name: 'Bonnie Lafazan' },
  { email: 'jodi@jodimurnick.com', school: 'usc', persona: 'parent', full_name: 'Jodi Murnick' },
  { email: 'alyciakaufmanwright@gmail.com', school: 'psu', persona: 'alumni', full_name: 'alycia kaufman' },
  { email: 'natalie@novawebgroup.com', school: 'psu', persona: 'alumni', full_name: 'Natalie Rose' },
  { email: 'nancyrmartin4@gmail.com', school: 'miami', persona: 'parent', full_name: 'nancy martin' },
  { email: 'jarahwilk@gmail.com', school: 'osu', persona: 'parent', full_name: 'Jarah Wilk' },
  { email: 'arleengoldenberg@gmail.com', school: 'fsu', persona: 'parent', full_name: 'Arleen Goldenberg' },
  { email: 'loridubin2@gmail.com', school: 'osu', persona: 'parent', full_name: 'Lori Dubin' },
  { email: 'mlb379@gmail.com', school: 'ucf', persona: 'parent', full_name: 'Mandi Blaire' },
  { email: 'jaime0525@gmail.com', school: 'umd', persona: 'parent', full_name: 'jaime shenkman' },
  { email: 'shillmant@bellsouth.net', school: 'miami', persona: 'parent', full_name: 'shillmant' },
  { email: 'levinteam@gmail.com', school: 'psu', persona: 'parent', full_name: 'jaime levin' },
  { email: 'josinoff@gmail.com', school: 'usc', persona: 'parent', full_name: 'Jill Osinoff' },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));
    const dryRun = body.dryRun !== false;
    const schoolFilter = body.schoolFilter || null;
    const offset = body.offset || 0;
    const batchSize = body.batchSize || 20;

    // Get existing users so we skip already-registered ones
    const existingUsers = await base44.asServiceRole.entities.User.list();
    const existingEmails = new Set((existingUsers || []).map(u => (u.email || '').toLowerCase().trim()));

    // Filter CSV to only people not already in the DB
    let toImport = CSV_USERS.filter(u => {
      const email = u.email.toLowerCase().trim();
      // Skip Apple relay emails — they can't receive email invites
      if (email.includes('privaterelay.appleid.com')) return false;
      if (existingEmails.has(email)) return false;
      if (schoolFilter && u.school !== schoolFilter) return false;
      return true;
    });

    const totalToImport = toImport.length;

    if (dryRun) {
      const bySchool = {};
      for (const u of toImport) {
        bySchool[u.school] = (bySchool[u.school] || 0) + 1;
      }
      return Response.json({
        dryRun: true,
        totalEligible: totalToImport,
        alreadyInDB: CSV_USERS.length - totalToImport,
        bySchool,
        sample: toImport.slice(0, 10).map(u => ({ email: u.email, school: u.school, persona: u.persona, full_name: u.full_name })),
      });
    }

    // Take the batch
    const batch = toImport.slice(offset, offset + batchSize);
    const results = { invited: [], failed: [], skipped: [] };

    for (const csvUser of batch) {
      try {
        await base44.users.inviteUser(csvUser.email, 'user');
        results.invited.push(csvUser.email);
        await new Promise(r => setTimeout(r, 300)); // rate limit
      } catch (err) {
        if (err.message?.includes('already') || err.message?.includes('exists')) {
          results.skipped.push(csvUser.email);
        } else {
          results.failed.push({ email: csvUser.email, error: err.message });
        }
      }
    }

    const nextOffset = offset + batchSize;
    return Response.json({
      dryRun: false,
      offset,
      batchSize,
      processed: batch.length,
      invited: results.invited.length,
      skipped: results.skipped.length,
      failed: results.failed.length,
      failedDetails: results.failed,
      hasMore: nextOffset < totalToImport,
      nextOffset,
      totalEligible: totalToImport,
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});